set SynModuleInfo {
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_3 MODELNAME GBM_Pipeline_VITIS_LOOP_28_3 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_3
    SUBMODULES {
      {MODELNAME GBM_dadd_64ns_64ns_64_5_full_dsp_1 RTLNAME GBM_dadd_64ns_64ns_64_5_full_dsp_1 BINDTYPE op TYPE dadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME GBM_dmul_64ns_64ns_64_5_max_dsp_1 RTLNAME GBM_dmul_64ns_64ns_64_5_max_dsp_1 BINDTYPE op TYPE dmul IMPL maxdsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME GBM_dexp_64ns_64ns_64_12_full_dsp_1 RTLNAME GBM_dexp_64ns_64ns_64_12_full_dsp_1 BINDTYPE op TYPE dexp IMPL fulldsp LATENCY 11 ALLOW_PRAGMA 1}
      {MODELNAME GBM_flow_control_loop_pipe_sequential_init RTLNAME GBM_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME GBM_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_31 MODELNAME GBM_Pipeline_VITIS_LOOP_28_31 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_31}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_32 MODELNAME GBM_Pipeline_VITIS_LOOP_28_32 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_32}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_33 MODELNAME GBM_Pipeline_VITIS_LOOP_28_33 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_33}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_34 MODELNAME GBM_Pipeline_VITIS_LOOP_28_34 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_34}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_35 MODELNAME GBM_Pipeline_VITIS_LOOP_28_35 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_35}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_36 MODELNAME GBM_Pipeline_VITIS_LOOP_28_36 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_36}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_37 MODELNAME GBM_Pipeline_VITIS_LOOP_28_37 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_37}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_38 MODELNAME GBM_Pipeline_VITIS_LOOP_28_38 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_38}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_39 MODELNAME GBM_Pipeline_VITIS_LOOP_28_39 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_39}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_310 MODELNAME GBM_Pipeline_VITIS_LOOP_28_310 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_310}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_311 MODELNAME GBM_Pipeline_VITIS_LOOP_28_311 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_311}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_312 MODELNAME GBM_Pipeline_VITIS_LOOP_28_312 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_312}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_313 MODELNAME GBM_Pipeline_VITIS_LOOP_28_313 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_313}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_314 MODELNAME GBM_Pipeline_VITIS_LOOP_28_314 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_314}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_315 MODELNAME GBM_Pipeline_VITIS_LOOP_28_315 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_315}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_316 MODELNAME GBM_Pipeline_VITIS_LOOP_28_316 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_316}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_317 MODELNAME GBM_Pipeline_VITIS_LOOP_28_317 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_317}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_318 MODELNAME GBM_Pipeline_VITIS_LOOP_28_318 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_318}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_319 MODELNAME GBM_Pipeline_VITIS_LOOP_28_319 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_319}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_320 MODELNAME GBM_Pipeline_VITIS_LOOP_28_320 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_320}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_321 MODELNAME GBM_Pipeline_VITIS_LOOP_28_321 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_321}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_322 MODELNAME GBM_Pipeline_VITIS_LOOP_28_322 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_322}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_323 MODELNAME GBM_Pipeline_VITIS_LOOP_28_323 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_323}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_324 MODELNAME GBM_Pipeline_VITIS_LOOP_28_324 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_324}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_325 MODELNAME GBM_Pipeline_VITIS_LOOP_28_325 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_325}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_326 MODELNAME GBM_Pipeline_VITIS_LOOP_28_326 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_326}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_327 MODELNAME GBM_Pipeline_VITIS_LOOP_28_327 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_327}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_328 MODELNAME GBM_Pipeline_VITIS_LOOP_28_328 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_328}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_329 MODELNAME GBM_Pipeline_VITIS_LOOP_28_329 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_329}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_330 MODELNAME GBM_Pipeline_VITIS_LOOP_28_330 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_330}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_331 MODELNAME GBM_Pipeline_VITIS_LOOP_28_331 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_331}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_332 MODELNAME GBM_Pipeline_VITIS_LOOP_28_332 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_332}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_333 MODELNAME GBM_Pipeline_VITIS_LOOP_28_333 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_333}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_334 MODELNAME GBM_Pipeline_VITIS_LOOP_28_334 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_334}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_335 MODELNAME GBM_Pipeline_VITIS_LOOP_28_335 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_335}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_336 MODELNAME GBM_Pipeline_VITIS_LOOP_28_336 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_336}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_337 MODELNAME GBM_Pipeline_VITIS_LOOP_28_337 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_337}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_338 MODELNAME GBM_Pipeline_VITIS_LOOP_28_338 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_338}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_339 MODELNAME GBM_Pipeline_VITIS_LOOP_28_339 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_339}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_340 MODELNAME GBM_Pipeline_VITIS_LOOP_28_340 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_340}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_341 MODELNAME GBM_Pipeline_VITIS_LOOP_28_341 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_341}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_342 MODELNAME GBM_Pipeline_VITIS_LOOP_28_342 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_342}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_343 MODELNAME GBM_Pipeline_VITIS_LOOP_28_343 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_343}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_344 MODELNAME GBM_Pipeline_VITIS_LOOP_28_344 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_344}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_345 MODELNAME GBM_Pipeline_VITIS_LOOP_28_345 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_345}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_346 MODELNAME GBM_Pipeline_VITIS_LOOP_28_346 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_346}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_347 MODELNAME GBM_Pipeline_VITIS_LOOP_28_347 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_347}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_348 MODELNAME GBM_Pipeline_VITIS_LOOP_28_348 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_348}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_349 MODELNAME GBM_Pipeline_VITIS_LOOP_28_349 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_349}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_350 MODELNAME GBM_Pipeline_VITIS_LOOP_28_350 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_350}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_351 MODELNAME GBM_Pipeline_VITIS_LOOP_28_351 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_351}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_352 MODELNAME GBM_Pipeline_VITIS_LOOP_28_352 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_352}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_353 MODELNAME GBM_Pipeline_VITIS_LOOP_28_353 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_353}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_354 MODELNAME GBM_Pipeline_VITIS_LOOP_28_354 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_354}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_355 MODELNAME GBM_Pipeline_VITIS_LOOP_28_355 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_355}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_356 MODELNAME GBM_Pipeline_VITIS_LOOP_28_356 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_356}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_357 MODELNAME GBM_Pipeline_VITIS_LOOP_28_357 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_357}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_358 MODELNAME GBM_Pipeline_VITIS_LOOP_28_358 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_358}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_359 MODELNAME GBM_Pipeline_VITIS_LOOP_28_359 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_359}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_360 MODELNAME GBM_Pipeline_VITIS_LOOP_28_360 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_360}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_361 MODELNAME GBM_Pipeline_VITIS_LOOP_28_361 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_361}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_362 MODELNAME GBM_Pipeline_VITIS_LOOP_28_362 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_362}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_363 MODELNAME GBM_Pipeline_VITIS_LOOP_28_363 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_363}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_364 MODELNAME GBM_Pipeline_VITIS_LOOP_28_364 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_364}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_365 MODELNAME GBM_Pipeline_VITIS_LOOP_28_365 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_365}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_366 MODELNAME GBM_Pipeline_VITIS_LOOP_28_366 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_366}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_367 MODELNAME GBM_Pipeline_VITIS_LOOP_28_367 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_367}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_368 MODELNAME GBM_Pipeline_VITIS_LOOP_28_368 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_368}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_369 MODELNAME GBM_Pipeline_VITIS_LOOP_28_369 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_369}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_370 MODELNAME GBM_Pipeline_VITIS_LOOP_28_370 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_370}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_371 MODELNAME GBM_Pipeline_VITIS_LOOP_28_371 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_371}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_372 MODELNAME GBM_Pipeline_VITIS_LOOP_28_372 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_372}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_373 MODELNAME GBM_Pipeline_VITIS_LOOP_28_373 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_373}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_374 MODELNAME GBM_Pipeline_VITIS_LOOP_28_374 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_374}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_375 MODELNAME GBM_Pipeline_VITIS_LOOP_28_375 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_375}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_376 MODELNAME GBM_Pipeline_VITIS_LOOP_28_376 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_376}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_377 MODELNAME GBM_Pipeline_VITIS_LOOP_28_377 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_377}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_378 MODELNAME GBM_Pipeline_VITIS_LOOP_28_378 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_378}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_379 MODELNAME GBM_Pipeline_VITIS_LOOP_28_379 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_379}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_380 MODELNAME GBM_Pipeline_VITIS_LOOP_28_380 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_380}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_381 MODELNAME GBM_Pipeline_VITIS_LOOP_28_381 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_381}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_382 MODELNAME GBM_Pipeline_VITIS_LOOP_28_382 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_382}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_383 MODELNAME GBM_Pipeline_VITIS_LOOP_28_383 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_383}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_384 MODELNAME GBM_Pipeline_VITIS_LOOP_28_384 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_384}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_385 MODELNAME GBM_Pipeline_VITIS_LOOP_28_385 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_385}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_386 MODELNAME GBM_Pipeline_VITIS_LOOP_28_386 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_386}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_387 MODELNAME GBM_Pipeline_VITIS_LOOP_28_387 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_387}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_388 MODELNAME GBM_Pipeline_VITIS_LOOP_28_388 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_388}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_389 MODELNAME GBM_Pipeline_VITIS_LOOP_28_389 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_389}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_390 MODELNAME GBM_Pipeline_VITIS_LOOP_28_390 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_390}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_391 MODELNAME GBM_Pipeline_VITIS_LOOP_28_391 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_391}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_392 MODELNAME GBM_Pipeline_VITIS_LOOP_28_392 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_392}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_393 MODELNAME GBM_Pipeline_VITIS_LOOP_28_393 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_393}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_394 MODELNAME GBM_Pipeline_VITIS_LOOP_28_394 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_394}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_395 MODELNAME GBM_Pipeline_VITIS_LOOP_28_395 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_395}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_396 MODELNAME GBM_Pipeline_VITIS_LOOP_28_396 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_396}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_397 MODELNAME GBM_Pipeline_VITIS_LOOP_28_397 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_397}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_398 MODELNAME GBM_Pipeline_VITIS_LOOP_28_398 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_398}
  {SRCNAME GBM_Pipeline_VITIS_LOOP_28_399 MODELNAME GBM_Pipeline_VITIS_LOOP_28_399 RTLNAME GBM_GBM_Pipeline_VITIS_LOOP_28_399}
  {SRCNAME GBM MODELNAME GBM RTLNAME GBM IS_TOP 1
    SUBMODULES {
      {MODELNAME GBM_dadddsub_64ns_64ns_64_5_full_dsp_1 RTLNAME GBM_dadddsub_64ns_64ns_64_5_full_dsp_1 BINDTYPE op TYPE dsub IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME GBM_ddiv_64ns_64ns_64_22_no_dsp_1 RTLNAME GBM_ddiv_64ns_64ns_64_22_no_dsp_1 BINDTYPE op TYPE ddiv IMPL fabric LATENCY 21 ALLOW_PRAGMA 1}
      {MODELNAME GBM_dsqrt_64ns_64ns_64_21_no_dsp_1 RTLNAME GBM_dsqrt_64ns_64ns_64_21_no_dsp_1 BINDTYPE op TYPE dsqrt IMPL fabric LATENCY 20 ALLOW_PRAGMA 1}
      {MODELNAME GBM_gmem_0_m_axi RTLNAME GBM_gmem_0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_1_m_axi RTLNAME GBM_gmem_1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_2_m_axi RTLNAME GBM_gmem_2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_3_m_axi RTLNAME GBM_gmem_3_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_4_m_axi RTLNAME GBM_gmem_4_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_5_m_axi RTLNAME GBM_gmem_5_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_6_m_axi RTLNAME GBM_gmem_6_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_7_m_axi RTLNAME GBM_gmem_7_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_8_m_axi RTLNAME GBM_gmem_8_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_9_m_axi RTLNAME GBM_gmem_9_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_10_m_axi RTLNAME GBM_gmem_10_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_11_m_axi RTLNAME GBM_gmem_11_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_12_m_axi RTLNAME GBM_gmem_12_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_13_m_axi RTLNAME GBM_gmem_13_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_14_m_axi RTLNAME GBM_gmem_14_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_15_m_axi RTLNAME GBM_gmem_15_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_16_m_axi RTLNAME GBM_gmem_16_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_17_m_axi RTLNAME GBM_gmem_17_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_18_m_axi RTLNAME GBM_gmem_18_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_19_m_axi RTLNAME GBM_gmem_19_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_20_m_axi RTLNAME GBM_gmem_20_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_21_m_axi RTLNAME GBM_gmem_21_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_22_m_axi RTLNAME GBM_gmem_22_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_23_m_axi RTLNAME GBM_gmem_23_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_24_m_axi RTLNAME GBM_gmem_24_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_25_m_axi RTLNAME GBM_gmem_25_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_26_m_axi RTLNAME GBM_gmem_26_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_27_m_axi RTLNAME GBM_gmem_27_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_28_m_axi RTLNAME GBM_gmem_28_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_29_m_axi RTLNAME GBM_gmem_29_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_30_m_axi RTLNAME GBM_gmem_30_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_31_m_axi RTLNAME GBM_gmem_31_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_32_m_axi RTLNAME GBM_gmem_32_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_33_m_axi RTLNAME GBM_gmem_33_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_34_m_axi RTLNAME GBM_gmem_34_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_35_m_axi RTLNAME GBM_gmem_35_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_36_m_axi RTLNAME GBM_gmem_36_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_37_m_axi RTLNAME GBM_gmem_37_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_38_m_axi RTLNAME GBM_gmem_38_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_39_m_axi RTLNAME GBM_gmem_39_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_40_m_axi RTLNAME GBM_gmem_40_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_41_m_axi RTLNAME GBM_gmem_41_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_42_m_axi RTLNAME GBM_gmem_42_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_43_m_axi RTLNAME GBM_gmem_43_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_44_m_axi RTLNAME GBM_gmem_44_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_45_m_axi RTLNAME GBM_gmem_45_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_46_m_axi RTLNAME GBM_gmem_46_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_47_m_axi RTLNAME GBM_gmem_47_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_48_m_axi RTLNAME GBM_gmem_48_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_49_m_axi RTLNAME GBM_gmem_49_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_50_m_axi RTLNAME GBM_gmem_50_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_51_m_axi RTLNAME GBM_gmem_51_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_52_m_axi RTLNAME GBM_gmem_52_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_53_m_axi RTLNAME GBM_gmem_53_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_54_m_axi RTLNAME GBM_gmem_54_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_55_m_axi RTLNAME GBM_gmem_55_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_56_m_axi RTLNAME GBM_gmem_56_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_57_m_axi RTLNAME GBM_gmem_57_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_58_m_axi RTLNAME GBM_gmem_58_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_59_m_axi RTLNAME GBM_gmem_59_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_60_m_axi RTLNAME GBM_gmem_60_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_61_m_axi RTLNAME GBM_gmem_61_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_62_m_axi RTLNAME GBM_gmem_62_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_63_m_axi RTLNAME GBM_gmem_63_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_64_m_axi RTLNAME GBM_gmem_64_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_65_m_axi RTLNAME GBM_gmem_65_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_66_m_axi RTLNAME GBM_gmem_66_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_67_m_axi RTLNAME GBM_gmem_67_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_68_m_axi RTLNAME GBM_gmem_68_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_69_m_axi RTLNAME GBM_gmem_69_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_70_m_axi RTLNAME GBM_gmem_70_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_71_m_axi RTLNAME GBM_gmem_71_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_72_m_axi RTLNAME GBM_gmem_72_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_73_m_axi RTLNAME GBM_gmem_73_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_74_m_axi RTLNAME GBM_gmem_74_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_75_m_axi RTLNAME GBM_gmem_75_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_76_m_axi RTLNAME GBM_gmem_76_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_77_m_axi RTLNAME GBM_gmem_77_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_78_m_axi RTLNAME GBM_gmem_78_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_79_m_axi RTLNAME GBM_gmem_79_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_80_m_axi RTLNAME GBM_gmem_80_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_81_m_axi RTLNAME GBM_gmem_81_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_82_m_axi RTLNAME GBM_gmem_82_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_83_m_axi RTLNAME GBM_gmem_83_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_84_m_axi RTLNAME GBM_gmem_84_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_85_m_axi RTLNAME GBM_gmem_85_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_86_m_axi RTLNAME GBM_gmem_86_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_87_m_axi RTLNAME GBM_gmem_87_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_88_m_axi RTLNAME GBM_gmem_88_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_89_m_axi RTLNAME GBM_gmem_89_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_90_m_axi RTLNAME GBM_gmem_90_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_91_m_axi RTLNAME GBM_gmem_91_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_92_m_axi RTLNAME GBM_gmem_92_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_93_m_axi RTLNAME GBM_gmem_93_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_94_m_axi RTLNAME GBM_gmem_94_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_95_m_axi RTLNAME GBM_gmem_95_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_96_m_axi RTLNAME GBM_gmem_96_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_97_m_axi RTLNAME GBM_gmem_97_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_98_m_axi RTLNAME GBM_gmem_98_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_gmem_99_m_axi RTLNAME GBM_gmem_99_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME GBM_control_s_axi RTLNAME GBM_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
