// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module SABR_pow_generic_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        base_r,
        exp,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [63:0] base_r;
input  [63:0] exp;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [5:0] pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_address0;
wire   [5:0] pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log0_lut_table_array_address0;
wire   [108:0] pow_reduce_anonymous_namespace_log0_lut_table_array_q0;
wire   [3:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_address0;
wire   [104:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_address0;
wire   [101:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_address0;
wire   [96:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_address0;
wire   [91:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_address0;
wire   [86:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_address0;
wire   [81:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_q0;
wire   [5:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_address0;
wire   [76:0] pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_q0;
wire   [7:0] pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_address0;
wire   [57:0] pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_q0;
wire   [7:0] pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_address0;
wire   [25:0] pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_q0;
wire   [7:0] pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_address1;
wire   [25:0] pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_q1;
wire   [7:0] pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_address0;
wire   [41:0] pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_q0;
reg   [63:0] exp_read_reg_2960;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] exp_read_reg_2960_pp0_iter1_reg;
reg   [63:0] exp_read_reg_2960_pp0_iter2_reg;
reg   [63:0] exp_read_reg_2960_pp0_iter3_reg;
reg   [63:0] exp_read_reg_2960_pp0_iter4_reg;
reg   [63:0] exp_read_reg_2960_pp0_iter5_reg;
reg   [63:0] exp_read_reg_2960_pp0_iter6_reg;
reg   [63:0] exp_read_reg_2960_pp0_iter7_reg;
reg   [63:0] exp_read_reg_2960_pp0_iter8_reg;
reg   [63:0] exp_read_reg_2960_pp0_iter9_reg;
reg   [10:0] bs_exp_reg_2965;
reg   [10:0] bs_exp_reg_2965_pp0_iter1_reg;
reg   [10:0] bs_exp_reg_2965_pp0_iter2_reg;
reg   [10:0] bs_exp_reg_2965_pp0_iter3_reg;
reg   [10:0] bs_exp_reg_2965_pp0_iter4_reg;
reg   [10:0] bs_exp_reg_2965_pp0_iter5_reg;
reg   [10:0] bs_exp_reg_2965_pp0_iter6_reg;
reg   [10:0] bs_exp_reg_2965_pp0_iter7_reg;
reg   [10:0] bs_exp_reg_2965_pp0_iter8_reg;
wire   [51:0] bs_sig_fu_674_p1;
reg   [51:0] bs_sig_reg_2972;
reg   [0:0] tmp_reg_2980;
reg   [0:0] tmp_reg_2980_pp0_iter1_reg;
reg   [0:0] tmp_reg_2980_pp0_iter2_reg;
reg   [0:0] tmp_reg_2980_pp0_iter3_reg;
reg   [0:0] tmp_reg_2980_pp0_iter4_reg;
reg   [0:0] tmp_reg_2980_pp0_iter5_reg;
reg   [0:0] tmp_reg_2980_pp0_iter6_reg;
reg   [0:0] tmp_reg_2980_pp0_iter7_reg;
reg   [0:0] tmp_reg_2980_pp0_iter8_reg;
reg   [0:0] tmp_reg_2980_pp0_iter9_reg;
reg   [0:0] tmp_5_reg_2987;
reg   [0:0] tmp_5_reg_2987_pp0_iter1_reg;
reg   [0:0] tmp_5_reg_2987_pp0_iter2_reg;
reg   [0:0] tmp_5_reg_2987_pp0_iter3_reg;
reg   [0:0] tmp_5_reg_2987_pp0_iter4_reg;
reg   [0:0] tmp_5_reg_2987_pp0_iter5_reg;
reg   [0:0] tmp_5_reg_2987_pp0_iter6_reg;
reg   [0:0] tmp_5_reg_2987_pp0_iter7_reg;
reg   [0:0] tmp_5_reg_2987_pp0_iter8_reg;
wire   [63:0] zext_ln502_fu_704_p1;
reg   [63:0] zext_ln502_reg_2993;
reg   [63:0] zext_ln502_reg_2993_pp0_iter1_reg;
reg   [63:0] zext_ln502_reg_2993_pp0_iter2_reg;
reg   [63:0] zext_ln502_reg_2993_pp0_iter3_reg;
reg   [63:0] zext_ln502_reg_2993_pp0_iter4_reg;
reg   [63:0] zext_ln502_reg_2993_pp0_iter5_reg;
reg   [63:0] zext_ln502_reg_2993_pp0_iter6_reg;
reg   [63:0] zext_ln502_reg_2993_pp0_iter7_reg;
wire   [0:0] icmp_ln340_1_fu_709_p2;
reg   [0:0] icmp_ln340_1_reg_3003;
reg   [0:0] icmp_ln340_1_reg_3003_pp0_iter2_reg;
reg   [0:0] icmp_ln340_1_reg_3003_pp0_iter3_reg;
reg   [0:0] icmp_ln340_1_reg_3003_pp0_iter4_reg;
reg   [0:0] icmp_ln340_1_reg_3003_pp0_iter5_reg;
reg   [0:0] icmp_ln340_1_reg_3003_pp0_iter6_reg;
reg   [0:0] icmp_ln340_1_reg_3003_pp0_iter7_reg;
reg   [0:0] icmp_ln340_1_reg_3003_pp0_iter8_reg;
reg   [0:0] icmp_ln340_1_reg_3003_pp0_iter9_reg;
wire   [0:0] icmp_ln18_4_fu_714_p2;
reg   [0:0] icmp_ln18_4_reg_3009;
reg   [0:0] icmp_ln18_4_reg_3009_pp0_iter2_reg;
reg   [0:0] icmp_ln18_4_reg_3009_pp0_iter3_reg;
reg   [0:0] icmp_ln18_4_reg_3009_pp0_iter4_reg;
reg   [0:0] icmp_ln18_4_reg_3009_pp0_iter5_reg;
reg   [0:0] icmp_ln18_4_reg_3009_pp0_iter6_reg;
reg   [0:0] icmp_ln18_4_reg_3009_pp0_iter7_reg;
reg   [0:0] icmp_ln18_4_reg_3009_pp0_iter8_reg;
reg   [0:0] icmp_ln18_4_reg_3009_pp0_iter9_reg;
wire   [53:0] mul_ln516_fu_630_p2;
reg   [53:0] mul_ln516_reg_3014;
reg   [3:0] a_reg_3020;
reg   [3:0] a_reg_3020_pp0_iter2_reg;
reg   [3:0] a_reg_3020_pp0_iter3_reg;
reg   [3:0] a_reg_3020_pp0_iter4_reg;
reg   [3:0] a_reg_3020_pp0_iter5_reg;
reg   [3:0] a_reg_3020_pp0_iter6_reg;
reg   [3:0] a_reg_3020_pp0_iter7_reg;
wire   [49:0] trunc_ln39_fu_762_p1;
reg   [49:0] trunc_ln39_reg_3026;
reg   [0:0] tmp_6_reg_3031;
reg   [72:0] z2_reg_3036;
reg   [5:0] a_1_reg_3042;
reg   [5:0] a_1_reg_3042_pp0_iter3_reg;
reg   [5:0] a_1_reg_3042_pp0_iter4_reg;
reg   [5:0] a_1_reg_3042_pp0_iter5_reg;
reg   [5:0] a_1_reg_3042_pp0_iter6_reg;
reg   [5:0] a_1_reg_3042_pp0_iter7_reg;
reg   [66:0] tmp_7_reg_3048;
wire   [81:0] sub_ln44_1_fu_941_p2;
reg   [81:0] sub_ln44_1_reg_3053;
reg   [5:0] a_2_reg_3058;
reg   [5:0] a_2_reg_3058_pp0_iter4_reg;
reg   [5:0] a_2_reg_3058_pp0_iter5_reg;
reg   [5:0] a_2_reg_3058_pp0_iter6_reg;
reg   [5:0] a_2_reg_3058_pp0_iter7_reg;
wire   [75:0] trunc_ln39_1_fu_957_p1;
reg   [75:0] trunc_ln39_1_reg_3064;
reg   [91:0] z4_reg_3069;
reg   [85:0] tmp_8_reg_3075;
reg   [5:0] tmp_9_reg_3080;
reg   [5:0] tmp_9_reg_3080_pp0_iter5_reg;
reg   [5:0] tmp_9_reg_3080_pp0_iter6_reg;
reg   [5:0] tmp_9_reg_3080_pp0_iter7_reg;
reg   [86:0] tmp_10_reg_3086;
reg   [80:0] tmp_11_reg_3092;
reg   [5:0] tmp_13_reg_3097;
reg   [5:0] tmp_13_reg_3097_pp0_iter6_reg;
reg   [5:0] tmp_13_reg_3097_pp0_iter7_reg;
reg   [81:0] tmp_14_reg_3103;
reg   [75:0] tmp_15_reg_3109;
reg   [5:0] tmp_16_reg_3114;
reg   [5:0] tmp_16_reg_3114_pp0_iter7_reg;
reg   [76:0] tmp_17_reg_3120;
reg   [70:0] tmp_18_reg_3126;
reg   [5:0] tmp_19_reg_3131;
reg   [71:0] tmp_20_reg_3177;
reg   [39:0] tmp_21_reg_3182;
wire   [0:0] x_is_1_fu_1443_p2;
reg   [0:0] x_is_1_reg_3187;
wire   [0:0] icmp_ln18_3_fu_1448_p2;
reg   [0:0] icmp_ln18_3_reg_3193;
wire   [0:0] x_is_0_fu_1453_p2;
reg   [0:0] x_is_0_reg_3199;
reg   [0:0] tmp_2_reg_3206;
reg  signed [77:0] log_base_reg_3213;
wire   [10:0] es_exp_fu_1661_p3;
reg   [10:0] es_exp_reg_3218;
wire  signed [11:0] m_exp_fu_1677_p2;
reg  signed [11:0] m_exp_reg_3223;
wire   [0:0] x_is_n1_fu_1699_p2;
reg   [0:0] x_is_n1_reg_3233;
reg   [0:0] x_is_n1_reg_3233_pp0_iter11_reg;
reg   [0:0] x_is_n1_reg_3233_pp0_iter12_reg;
reg   [0:0] x_is_n1_reg_3233_pp0_iter13_reg;
reg   [0:0] x_is_n1_reg_3233_pp0_iter14_reg;
reg   [0:0] x_is_n1_reg_3233_pp0_iter15_reg;
reg   [0:0] x_is_n1_reg_3233_pp0_iter16_reg;
reg   [0:0] x_is_n1_reg_3233_pp0_iter17_reg;
reg   [0:0] x_is_n1_reg_3233_pp0_iter18_reg;
wire   [0:0] x_is_neg_fu_1752_p2;
reg   [0:0] x_is_neg_reg_3239;
wire   [0:0] tmp_1_fu_1763_p3;
reg   [0:0] tmp_1_reg_3244;
wire   [0:0] or_ln378_1_fu_1861_p2;
reg   [0:0] or_ln378_1_reg_3252;
reg   [0:0] or_ln378_1_reg_3252_pp0_iter11_reg;
reg   [0:0] or_ln378_1_reg_3252_pp0_iter12_reg;
reg   [0:0] or_ln378_1_reg_3252_pp0_iter13_reg;
reg   [0:0] or_ln378_1_reg_3252_pp0_iter14_reg;
reg   [0:0] or_ln378_1_reg_3252_pp0_iter15_reg;
reg   [0:0] or_ln378_1_reg_3252_pp0_iter16_reg;
reg   [0:0] or_ln378_1_reg_3252_pp0_iter17_reg;
reg   [0:0] or_ln378_1_reg_3252_pp0_iter18_reg;
wire   [0:0] or_ln386_2_fu_1891_p2;
reg   [0:0] or_ln386_2_reg_3259;
reg   [0:0] or_ln386_2_reg_3259_pp0_iter11_reg;
reg   [0:0] or_ln386_2_reg_3259_pp0_iter12_reg;
reg   [0:0] or_ln386_2_reg_3259_pp0_iter13_reg;
reg   [0:0] or_ln386_2_reg_3259_pp0_iter14_reg;
reg   [0:0] or_ln386_2_reg_3259_pp0_iter15_reg;
reg   [0:0] or_ln386_2_reg_3259_pp0_iter16_reg;
reg   [0:0] or_ln386_2_reg_3259_pp0_iter17_reg;
reg   [0:0] or_ln386_2_reg_3259_pp0_iter18_reg;
wire   [0:0] y_is_odd_fu_1930_p3;
reg   [0:0] y_is_odd_reg_3265;
wire   [0:0] or_ln431_2_fu_1972_p2;
reg   [0:0] or_ln431_2_reg_3270;
reg   [0:0] or_ln431_2_reg_3270_pp0_iter11_reg;
reg   [0:0] or_ln431_2_reg_3270_pp0_iter12_reg;
reg   [0:0] or_ln431_2_reg_3270_pp0_iter13_reg;
reg   [0:0] or_ln431_2_reg_3270_pp0_iter14_reg;
reg   [0:0] or_ln431_2_reg_3270_pp0_iter15_reg;
reg   [0:0] or_ln431_2_reg_3270_pp0_iter16_reg;
reg   [0:0] or_ln431_2_reg_3270_pp0_iter17_reg;
reg   [0:0] or_ln431_2_reg_3270_pp0_iter18_reg;
wire   [0:0] or_ln438_2_fu_2012_p2;
reg   [0:0] or_ln438_2_reg_3276;
reg   [0:0] or_ln438_2_reg_3276_pp0_iter11_reg;
reg   [0:0] or_ln438_2_reg_3276_pp0_iter12_reg;
reg   [0:0] or_ln438_2_reg_3276_pp0_iter13_reg;
reg   [0:0] or_ln438_2_reg_3276_pp0_iter14_reg;
reg   [0:0] or_ln438_2_reg_3276_pp0_iter15_reg;
reg   [0:0] or_ln438_2_reg_3276_pp0_iter16_reg;
reg   [0:0] or_ln438_2_reg_3276_pp0_iter17_reg;
reg   [0:0] or_ln438_2_reg_3276_pp0_iter18_reg;
wire   [130:0] m_frac_l_fu_642_p2;
reg   [130:0] m_frac_l_reg_3282;
reg   [0:0] tmp_30_reg_3292;
reg   [0:0] tmp_30_reg_3292_pp0_iter11_reg;
reg   [0:0] tmp_30_reg_3292_pp0_iter12_reg;
reg   [0:0] tmp_30_reg_3292_pp0_iter13_reg;
reg   [0:0] tmp_30_reg_3292_pp0_iter14_reg;
reg   [0:0] tmp_30_reg_3292_pp0_iter15_reg;
reg   [0:0] tmp_30_reg_3292_pp0_iter16_reg;
reg   [0:0] tmp_30_reg_3292_pp0_iter17_reg;
reg   [0:0] tmp_30_reg_3292_pp0_iter18_reg;
wire   [0:0] icmp_ln422_fu_2066_p2;
reg   [0:0] icmp_ln422_reg_3298;
reg   [0:0] icmp_ln422_reg_3298_pp0_iter12_reg;
reg   [0:0] icmp_ln422_reg_3298_pp0_iter13_reg;
reg   [0:0] icmp_ln422_reg_3298_pp0_iter14_reg;
reg   [0:0] icmp_ln422_reg_3298_pp0_iter15_reg;
reg   [0:0] icmp_ln422_reg_3298_pp0_iter16_reg;
reg   [0:0] icmp_ln422_reg_3298_pp0_iter17_reg;
reg   [0:0] icmp_ln422_reg_3298_pp0_iter18_reg;
wire   [0:0] r_sign_fu_2121_p2;
reg   [0:0] r_sign_reg_3303;
reg   [0:0] r_sign_reg_3303_pp0_iter12_reg;
reg   [0:0] r_sign_reg_3303_pp0_iter13_reg;
reg   [0:0] r_sign_reg_3303_pp0_iter14_reg;
reg   [0:0] r_sign_reg_3303_pp0_iter15_reg;
reg   [0:0] r_sign_reg_3303_pp0_iter16_reg;
reg   [0:0] r_sign_reg_3303_pp0_iter17_reg;
reg   [0:0] r_sign_reg_3303_pp0_iter18_reg;
reg   [58:0] m_fix_reg_3311;
reg   [58:0] m_fix_reg_3311_pp0_iter12_reg;
reg   [58:0] m_fix_reg_3311_pp0_iter13_reg;
reg   [58:0] m_fix_reg_3311_pp0_iter14_reg;
reg   [0:0] tmp_23_reg_3316;
reg   [0:0] tmp_23_reg_3316_pp0_iter12_reg;
wire   [0:0] icmp_ln628_fu_2301_p2;
reg   [0:0] icmp_ln628_reg_3326;
reg   [0:0] icmp_ln628_reg_3326_pp0_iter12_reg;
reg   [0:0] icmp_ln628_reg_3326_pp0_iter13_reg;
reg   [0:0] icmp_ln628_reg_3326_pp0_iter14_reg;
reg   [0:0] icmp_ln628_reg_3326_pp0_iter15_reg;
reg   [0:0] icmp_ln628_reg_3326_pp0_iter16_reg;
reg   [0:0] icmp_ln628_reg_3326_pp0_iter17_reg;
reg   [0:0] icmp_ln628_reg_3326_pp0_iter18_reg;
wire  signed [12:0] r_exp_fu_2356_p3;
reg  signed [12:0] r_exp_reg_3336;
reg  signed [12:0] r_exp_reg_3336_pp0_iter15_reg;
reg  signed [12:0] r_exp_reg_3336_pp0_iter16_reg;
reg  signed [12:0] r_exp_reg_3336_pp0_iter17_reg;
reg   [7:0] m_diff_hi_reg_3343;
reg   [7:0] m_diff_hi_reg_3343_pp0_iter16_reg;
reg   [7:0] Z2_reg_3348;
reg   [7:0] Z2_reg_3348_pp0_iter16_reg;
wire   [7:0] Z3_fu_2403_p4;
reg   [7:0] Z3_reg_3355;
wire   [34:0] Z4_fu_2413_p1;
reg   [34:0] Z4_reg_3360;
wire   [42:0] exp_Z3_m_1_fu_2460_p4;
reg   [42:0] exp_Z3_m_1_reg_3375;
wire   [35:0] add_ln261_fu_2493_p2;
reg   [35:0] add_ln261_reg_3380;
reg   [49:0] exp_Z1P_m_1_reg_3395;
wire   [0:0] icmp_ln628_1_fu_2676_p2;
reg   [0:0] icmp_ln628_1_reg_3400;
wire   [0:0] icmp_ln645_fu_2682_p2;
reg   [0:0] icmp_ln645_reg_3405;
wire   [51:0] out_sig_fu_2708_p3;
reg   [51:0] out_sig_reg_3410;
wire   [10:0] trunc_ln657_fu_2716_p1;
reg   [10:0] trunc_ln657_reg_3415;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln46_fu_1322_p1;
wire   [63:0] zext_ln46_1_fu_1326_p1;
wire   [63:0] zext_ln46_2_fu_1330_p1;
wire   [63:0] zext_ln46_3_fu_1334_p1;
wire   [63:0] zext_ln46_4_fu_1338_p1;
wire   [63:0] zext_ln46_5_fu_1342_p1;
wire   [63:0] zext_ln46_6_fu_1404_p1;
wire   [63:0] zext_ln249_fu_2427_p1;
wire   [63:0] zext_ln254_fu_2432_p1;
wire   [63:0] zext_ln273_fu_2499_p1;
wire   [63:0] zext_ln611_fu_2503_p1;
reg    pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local;
reg    pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_ce0_local;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_ce0_local;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_ce0_local;
reg    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_ce0_local;
reg    pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_ce1_local;
reg    pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_ce0_local;
reg    pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local;
reg    pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local;
wire   [79:0] Elog2_fu_604_p1;
wire   [39:0] mul_ln522_fu_614_p0;
wire   [78:0] zext_ln522_fu_1566_p1;
wire   [39:0] mul_ln522_fu_614_p1;
wire   [42:0] mul_ln258_fu_618_p0;
wire   [35:0] mul_ln258_fu_618_p1;
wire   [48:0] mul_ln277_fu_622_p0;
wire   [43:0] mul_ln277_fu_622_p1;
wire   [49:0] mul_ln616_fu_626_p0;
wire   [49:0] mul_ln616_fu_626_p1;
wire  signed [53:0] mul_ln516_fu_630_p0;
wire   [5:0] mul_ln516_fu_630_p1;
wire   [72:0] mul_ln44_1_fu_634_p0;
wire   [5:0] mul_ln44_1_fu_634_p1;
wire   [76:0] mul_ln44_6_fu_638_p0;
wire   [5:0] mul_ln44_6_fu_638_p1;
wire   [81:0] mul_ln44_5_fu_646_p0;
wire   [5:0] mul_ln44_5_fu_646_p1;
wire   [82:0] mul_ln44_2_fu_650_p0;
wire   [5:0] mul_ln44_2_fu_650_p1;
wire   [86:0] mul_ln44_4_fu_654_p0;
wire   [5:0] mul_ln44_4_fu_654_p1;
wire   [91:0] mul_ln44_3_fu_658_p0;
wire   [5:0] mul_ln44_3_fu_658_p1;
wire   [63:0] data_fu_662_p1;
wire   [5:0] index0_fu_694_p4;
wire   [52:0] b_frac_1_fu_728_p3;
wire   [53:0] zext_ln485_fu_735_p1;
wire   [53:0] b_frac_fu_719_p4;
wire   [69:0] tmp_s_fu_781_p3;
wire   [73:0] zext_ln42_fu_788_p1;
wire   [70:0] z1_fu_774_p3;
wire   [74:0] zext_ln42_1_fu_800_p1;
wire   [74:0] zext_ln42_2_cast_fu_792_p3;
wire   [75:0] tmp_4_fu_804_p3;
wire   [75:0] zext_ln42_2_fu_812_p1;
wire   [74:0] shl_ln_fu_823_p3;
wire   [75:0] zext_ln44_fu_830_p1;
wire   [75:0] select_ln42_fu_816_p3;
wire   [70:0] mul_ln44_fu_843_p0;
wire   [3:0] mul_ln44_fu_843_p1;
wire   [74:0] mul_ln44_fu_843_p2;
wire   [75:0] add_ln44_fu_834_p2;
wire   [75:0] zext_ln44_2_fu_849_p1;
wire   [75:0] sub_ln44_fu_853_p2;
wire   [79:0] zext_ln40_fu_889_p1;
wire   [80:0] shl_ln44_1_fu_900_p3;
wire   [80:0] eZ_fu_892_p3;
wire   [81:0] zext_ln44_3_fu_907_p1;
wire   [81:0] zext_ln44_4_fu_911_p1;
wire   [78:0] mul_ln44_1_fu_634_p2;
wire   [79:0] shl_ln44_2_fu_929_p3;
wire   [81:0] add_ln44_1_fu_915_p2;
wire   [81:0] zext_ln44_7_fu_937_p1;
wire   [82:0] z3_fu_961_p3;
wire   [94:0] zext_ln40_1_fu_968_p1;
wire   [100:0] shl_ln44_4_fu_980_p3;
wire   [95:0] eZ_1_fu_972_p3;
wire   [101:0] zext_ln44_8_fu_987_p1;
wire   [101:0] zext_ln44_9_fu_991_p1;
wire   [88:0] mul_ln44_2_fu_650_p2;
wire   [94:0] shl_ln44_5_fu_1010_p3;
wire   [101:0] add_ln44_2_fu_995_p2;
wire   [101:0] zext_ln44_12_fu_1018_p1;
wire   [101:0] sub_ln44_2_fu_1022_p2;
wire   [108:0] zext_ln40_2_fu_1058_p1;
wire   [119:0] shl_ln44_6_fu_1069_p3;
wire   [109:0] eZ_2_fu_1061_p3;
wire   [120:0] zext_ln44_13_fu_1076_p1;
wire   [120:0] zext_ln44_14_fu_1080_p1;
wire   [96:0] mul_ln44_3_fu_658_p2;
wire   [107:0] shl_ln44_7_fu_1098_p3;
wire   [120:0] add_ln44_3_fu_1084_p2;
wire   [120:0] zext_ln44_17_fu_1106_p1;
wire   [120:0] sub_ln44_3_fu_1110_p2;
wire   [108:0] zext_ln40_3_fu_1146_p1;
wire   [124:0] shl_ln44_8_fu_1157_p3;
wire   [109:0] eZ_3_fu_1149_p3;
wire   [125:0] zext_ln44_18_fu_1164_p1;
wire   [125:0] zext_ln44_19_fu_1168_p1;
wire   [91:0] mul_ln44_4_fu_654_p2;
wire   [107:0] shl_ln44_9_fu_1186_p3;
wire   [125:0] add_ln44_4_fu_1172_p2;
wire   [125:0] zext_ln44_22_fu_1194_p1;
wire   [125:0] sub_ln44_4_fu_1198_p2;
wire   [108:0] zext_ln40_4_fu_1234_p1;
wire   [129:0] shl_ln44_s_fu_1245_p3;
wire   [109:0] eZ_4_fu_1237_p3;
wire   [130:0] zext_ln44_23_fu_1252_p1;
wire   [130:0] zext_ln44_24_fu_1256_p1;
wire   [86:0] mul_ln44_5_fu_646_p2;
wire   [107:0] shl_ln44_3_fu_1274_p3;
wire   [130:0] add_ln44_5_fu_1260_p2;
wire   [130:0] zext_ln44_27_fu_1282_p1;
wire   [130:0] sub_ln44_5_fu_1286_p2;
wire   [108:0] zext_ln40_5_fu_1346_p1;
wire   [134:0] shl_ln44_10_fu_1357_p3;
wire   [109:0] eZ_5_fu_1349_p3;
wire   [135:0] zext_ln44_28_fu_1364_p1;
wire   [135:0] zext_ln44_29_fu_1368_p1;
wire   [81:0] mul_ln44_6_fu_638_p2;
wire   [107:0] shl_ln44_11_fu_1386_p3;
wire   [135:0] add_ln44_6_fu_1372_p2;
wire   [135:0] zext_ln44_32_fu_1394_p1;
wire   [135:0] sub_ln44_6_fu_1398_p2;
wire   [11:0] zext_ln486_fu_1428_p1;
wire   [11:0] b_exp_fu_1431_p2;
wire   [0:0] icmp_ln340_fu_1437_p2;
wire   [11:0] b_exp_1_fu_1466_p2;
wire  signed [11:0] b_exp_2_fu_1472_p3;
wire   [108:0] zext_ln194_fu_1484_p1;
wire   [102:0] zext_ln194_1_fu_1488_p1;
wire   [102:0] zext_ln194_2_fu_1492_p1;
wire   [102:0] add_ln209_1_fu_1518_p2;
wire   [108:0] zext_ln209_fu_1524_p1;
wire   [108:0] add_ln209_fu_1512_p2;
wire   [92:0] zext_ln194_3_fu_1496_p1;
wire   [92:0] zext_ln194_4_fu_1500_p1;
wire   [82:0] zext_ln194_5_fu_1504_p1;
wire   [82:0] zext_ln194_6_fu_1508_p1;
wire   [82:0] add_ln209_4_fu_1540_p2;
wire   [92:0] zext_ln209_1_fu_1546_p1;
wire   [92:0] add_ln209_3_fu_1534_p2;
wire   [92:0] add_ln209_5_fu_1550_p2;
wire   [108:0] zext_ln209_2_fu_1556_p1;
wire   [108:0] add_ln209_2_fu_1528_p2;
wire   [78:0] mul_ln522_fu_614_p2;
wire   [77:0] lshr_ln_fu_1571_p4;
wire   [116:0] shl_ln1_fu_1581_p3;
wire   [116:0] zext_ln522_1_fu_1588_p1;
wire   [116:0] sub_ln522_fu_1592_p2;
wire   [89:0] Elog2_fu_604_p2;
wire   [119:0] shl_ln2_fu_1608_p3;
wire   [108:0] log_sum_1_fu_1560_p2;
wire  signed [120:0] sext_ln525_fu_1616_p1;
wire  signed [120:0] sext_ln525_1_fu_1620_p1;
wire   [71:0] lshr_ln522_1_fu_1598_p4;
wire   [120:0] add_ln525_fu_1624_p2;
wire   [120:0] zext_ln525_fu_1630_p1;
wire   [120:0] add_ln525_1_fu_1634_p2;
wire   [63:0] data_1_fu_1650_p1;
wire   [11:0] zext_ln486_1_fu_1673_p1;
wire   [0:0] xor_ln341_fu_1689_p2;
wire   [51:0] es_sig_fu_1669_p1;
wire   [0:0] icmp_ln18_fu_1703_p2;
wire   [0:0] icmp_ln18_1_fu_1709_p2;
wire   [0:0] icmp_ln18_2_fu_1721_p2;
wire   [0:0] x_is_inf_fu_1737_p2;
wire   [0:0] or_ln357_fu_1741_p2;
wire   [0:0] xor_ln357_fu_1746_p2;
wire   [5:0] es_exp_cast_fu_1771_p4;
wire   [5:0] add_ln373_fu_1781_p2;
wire   [51:0] zext_ln373_fu_1787_p1;
wire   [51:0] lshr_ln373_fu_1791_p2;
wire   [51:0] and_ln373_1_fu_1797_p2;
wire   [0:0] icmp_ln372_fu_1757_p2;
wire   [0:0] or_ln373_fu_1809_p2;
wire   [0:0] xor_ln373_fu_1815_p2;
wire   [0:0] y_is_int_fu_1829_p4;
wire   [0:0] y_is_int_fu_1829_p7;
wire   [1:0] y_is_int_fu_1829_p8;
wire   [0:0] y_is_inf_fu_1715_p2;
wire   [0:0] x_is_p1_fu_1694_p2;
wire   [0:0] and_ln378_fu_1849_p2;
wire   [0:0] or_ln378_fu_1855_p2;
wire   [0:0] y_is_0_fu_1683_p2;
wire   [0:0] y_is_int_fu_1829_p9;
wire   [0:0] or_ln386_fu_1867_p2;
wire   [0:0] xor_ln386_fu_1873_p2;
wire   [0:0] x_is_NaN_fu_1733_p2;
wire   [0:0] and_ln386_fu_1879_p2;
wire   [0:0] or_ln386_1_fu_1885_p2;
wire   [0:0] y_is_NaN_fu_1727_p2;
wire   [0:0] es_sign_fu_1653_p3;
wire   [0:0] y_is_pos_fu_1897_p2;
wire   [11:0] sub_ln422_fu_1920_p2;
wire  signed [31:0] y_is_odd_fu_1930_p2;
wire   [0:0] y_is_pinf_fu_1903_p2;
wire   [0:0] x_abs_greater_1_fu_1915_p2;
wire   [0:0] y_is_ninf_fu_1909_p2;
wire   [0:0] and_ln431_2_fu_1949_p2;
wire   [0:0] and_ln431_fu_1938_p2;
wire   [0:0] or_ln431_fu_1960_p2;
wire   [0:0] and_ln431_3_fu_1955_p2;
wire   [0:0] or_ln431_1_fu_1966_p2;
wire   [0:0] and_ln431_1_fu_1944_p2;
wire   [0:0] and_ln438_2_fu_1989_p2;
wire   [0:0] and_ln438_1_fu_1983_p2;
wire   [0:0] or_ln438_fu_2000_p2;
wire   [0:0] and_ln438_3_fu_1994_p2;
wire   [0:0] or_ln438_1_fu_2006_p2;
wire   [0:0] and_ln438_fu_1978_p2;
wire   [52:0] e_frac_fu_2018_p3;
wire   [53:0] zext_ln532_fu_2026_p1;
wire   [53:0] e_frac_1_fu_2030_p2;
wire  signed [53:0] e_frac_2_fu_2036_p3;
wire   [0:0] icmp_ln421_fu_2061_p2;
wire   [0:0] icmp_ln422_1_fu_2071_p2;
wire   [0:0] xor_ln421_fu_2076_p2;
wire   [0:0] and_ln422_fu_2082_p2;
wire   [0:0] and_ln422_1_fu_2088_p2;
wire   [0:0] y_is_odd_1_fu_2102_p7;
wire   [1:0] y_is_odd_1_fu_2102_p8;
wire   [0:0] y_is_odd_1_fu_2102_p9;
wire  signed [10:0] sub_ln545_fu_2126_p2;
wire  signed [11:0] sext_ln545_fu_2131_p1;
wire   [11:0] select_ln545_fu_2135_p3;
wire  signed [31:0] sext_ln545_1_fu_2141_p1;
wire   [130:0] zext_ln545_fu_2145_p1;
wire   [130:0] ashr_ln545_fu_2149_p2;
wire   [130:0] shl_ln545_fu_2154_p2;
wire   [129:0] trunc_ln545_fu_2159_p1;
wire   [129:0] trunc_ln545_1_fu_2163_p1;
wire   [129:0] m_fix_l_fu_2167_p3;
wire   [129:0] zext_ln546_fu_2174_p1;
wire   [129:0] shl_ln546_fu_2178_p2;
wire   [129:0] ashr_ln546_fu_2184_p2;
wire  signed [31:0] sext_ln552_fu_2197_p1;
wire   [130:0] zext_ln552_fu_2200_p1;
wire   [0:0] tmp_22_fu_2209_p3;
wire   [11:0] select_ln553_fu_2217_p3;
wire  signed [31:0] sext_ln553_fu_2224_p1;
wire   [130:0] zext_ln553_fu_2228_p1;
wire   [130:0] shl_ln553_fu_2232_p2;
wire   [130:0] ashr_ln553_fu_2237_p2;
wire   [130:0] select_ln553_1_fu_2242_p3;
wire   [130:0] shl_ln552_fu_2204_p2;
wire   [130:0] m_fix_0_in_in_v_v_fu_2250_p3;
wire   [129:0] empty_fu_2257_p1;
wire   [130:0] zext_ln549_fu_2261_p1;
wire  signed [15:0] m_fix_hi_fu_2275_p4;
wire   [129:0] m_fix_back_fu_2190_p3;
wire  signed [130:0] sext_ln628_fu_2297_p1;
wire  signed [18:0] shl_ln3_fu_2306_p3;
wire  signed [30:0] grp_fu_2949_p3;
wire   [17:0] trunc_ln563_fu_2333_p1;
wire   [12:0] tmp_9_cast_fu_2317_p4;
wire   [0:0] icmp_ln563_fu_2336_p2;
wire   [12:0] add_ln563_1_fu_2342_p2;
wire   [0:0] tmp_24_fu_2326_p3;
wire   [12:0] select_ln563_fu_2348_p3;
wire   [70:0] mul_ln568_fu_609_p2;
wire   [58:0] m_fix_a_fu_2368_p4;
wire   [58:0] sub_ln574_fu_2378_p2;
wire   [7:0] Z4_ind_fu_2417_p4;
wire   [9:0] f_Z4_fu_2437_p4;
wire   [35:0] zext_ln250_fu_2447_p1;
wire   [35:0] zext_ln250_1_fu_2450_p1;
wire   [35:0] exp_Z4_m_1_fu_2454_p2;
wire   [78:0] mul_ln258_fu_618_p2;
wire   [19:0] tmp_25_fu_2479_p4;
wire   [35:0] zext_ln261_1_fu_2489_p1;
wire   [43:0] zext_ln261_fu_2510_p1;
wire   [43:0] zext_ln255_fu_2507_p1;
wire   [39:0] tmp_26_fu_2519_p4;
wire   [48:0] exp_Z2_m_1_fu_2529_p4;
wire   [43:0] exp_Z2P_m_1_fu_2513_p2;
wire   [50:0] and_ln_fu_2548_p5;
wire   [92:0] mul_ln277_fu_622_p2;
wire   [35:0] tmp_27_fu_2563_p4;
wire   [43:0] zext_ln280_2_fu_2573_p1;
wire   [43:0] add_ln280_fu_2577_p2;
wire   [51:0] zext_ln280_1_fu_2583_p1;
wire   [51:0] zext_ln280_fu_2559_p1;
wire   [51:0] exp_Z1P_m_1_l_fu_2587_p2;
wire   [49:0] exp_Z1_hi_fu_2603_p4;
wire   [57:0] add_ln616_fu_2613_p2;
wire   [98:0] mul_ln616_fu_626_p2;
wire   [106:0] shl_ln4_fu_2628_p3;
wire   [106:0] zext_ln616_2_fu_2636_p1;
wire   [106:0] add_ln616_1_fu_2640_p2;
wire   [0:0] tmp_28_fu_2646_p3;
wire   [12:0] r_exp_1_fu_2654_p2;
wire   [12:0] r_exp_2_fu_2659_p3;
wire   [2:0] tmp_29_fu_2666_p4;
wire   [51:0] tmp_3_fu_2688_p4;
wire   [51:0] tmp_12_fu_2698_p4;
wire   [63:0] t_fu_2720_p3;
wire   [63:0] t_1_fu_2741_p3;
wire   [63:0] t_2_fu_2752_p3;
wire   [0:0] and_ln628_fu_2763_p2;
wire   [10:0] out_exp_fu_2772_p2;
wire   [63:0] t_3_fu_2777_p4;
wire   [0:0] or_ln386_3_fu_2789_p2;
wire   [0:0] xor_ln386_1_fu_2793_p2;
wire   [0:0] xor_ln386_2_fu_2804_p2;
wire   [0:0] xor_ln342_fu_2814_p2;
wire   [0:0] and_ln342_1_fu_2819_p2;
wire   [0:0] xor_ln431_fu_2731_p2;
wire   [0:0] and_ln431_5_fu_2830_p2;
wire   [0:0] xor_ln438_fu_2736_p2;
wire   [0:0] and_ln438_5_fu_2841_p2;
wire   [0:0] or_ln628_fu_2767_p2;
wire   [0:0] and_ln628_1_fu_2847_p2;
wire   [0:0] xor_ln629_fu_2858_p2;
wire   [0:0] xor_ln628_fu_2869_p2;
wire   [0:0] and_ln645_fu_2875_p2;
wire   [0:0] and_ln342_fu_2799_p2;
wire   [0:0] and_ln386_1_fu_2809_p2;
wire   [0:0] and_ln431_4_fu_2825_p2;
wire   [0:0] and_ln438_4_fu_2836_p2;
wire   [0:0] and_ln629_fu_2853_p2;
wire   [0:0] and_ln629_1_fu_2863_p2;
wire   [0:0] and_ln645_1_fu_2880_p2;
wire   [63:0] retval_2_fu_2905_p4;
wire   [63:0] bitcast_ln497_1_fu_2748_p1;
wire   [63:0] bitcast_ln497_2_fu_2759_p1;
wire   [63:0] retval_2_fu_2905_p18;
wire   [63:0] retval_2_fu_2905_p19;
wire   [7:0] retval_2_fu_2905_p20;
wire   [14:0] grp_fu_2949_p1;
wire   [63:0] retval_2_fu_2905_p21;
reg    grp_fu_2949_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to18;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [78:0] mul_ln258_fu_618_p00;
wire   [78:0] mul_ln258_fu_618_p10;
wire   [92:0] mul_ln277_fu_622_p00;
wire   [92:0] mul_ln277_fu_622_p10;
wire   [78:0] mul_ln44_1_fu_634_p00;
wire   [78:0] mul_ln44_1_fu_634_p10;
wire   [88:0] mul_ln44_2_fu_650_p00;
wire   [88:0] mul_ln44_2_fu_650_p10;
wire   [96:0] mul_ln44_3_fu_658_p00;
wire   [96:0] mul_ln44_3_fu_658_p10;
wire   [91:0] mul_ln44_4_fu_654_p00;
wire   [91:0] mul_ln44_4_fu_654_p10;
wire   [86:0] mul_ln44_5_fu_646_p00;
wire   [86:0] mul_ln44_5_fu_646_p10;
wire   [81:0] mul_ln44_6_fu_638_p00;
wire   [81:0] mul_ln44_6_fu_638_p10;
wire   [74:0] mul_ln44_fu_843_p10;
wire   [53:0] mul_ln516_fu_630_p10;
wire   [98:0] mul_ln616_fu_626_p00;
wire   [98:0] mul_ln616_fu_626_p10;
wire  signed [1:0] y_is_int_fu_1829_p1;
wire   [1:0] y_is_int_fu_1829_p3;
wire   [1:0] y_is_int_fu_1829_p5;
wire   [0:0] y_is_odd_fu_1930_p0;
wire  signed [1:0] y_is_odd_1_fu_2102_p1;
wire   [1:0] y_is_odd_1_fu_2102_p3;
wire   [1:0] y_is_odd_1_fu_2102_p5;
wire  signed [7:0] retval_2_fu_2905_p1;
wire   [7:0] retval_2_fu_2905_p3;
wire   [7:0] retval_2_fu_2905_p5;
wire   [7:0] retval_2_fu_2905_p7;
wire   [7:0] retval_2_fu_2905_p9;
wire   [7:0] retval_2_fu_2905_p11;
wire   [7:0] retval_2_fu_2905_p13;
wire   [7:0] retval_2_fu_2905_p15;
wire   [7:0] retval_2_fu_2905_p17;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
end

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log_inverse_lut_table_powbkb #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log0_lut_table_array_ROM_cud #(
    .DataWidth( 109 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log0_lut_table_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log0_lut_table_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log0_lut_table_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_dEe #(
    .DataWidth( 105 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_eOg #(
    .DataWidth( 102 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12fYi #(
    .DataWidth( 97 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17g8j #(
    .DataWidth( 92 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22hbi #(
    .DataWidth( 87 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27ibs #(
    .DataWidth( 82 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32jbC #(
    .DataWidth( 77 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_address0),
    .ce0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_arkbM #(
    .DataWidth( 58 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_address0),
    .ce0(pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_q0)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_arralbW #(
    .DataWidth( 26 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_address0),
    .ce0(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_q0),
    .address1(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_address1),
    .ce1(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_ce1_local),
    .q1(pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_q1)
);

SABR_pow_generic_double_s_pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_arramb6 #(
    .DataWidth( 42 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_address0),
    .ce0(pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local),
    .q0(pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_q0)
);

SABR_mul_12s_80ns_90_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 80 ),
    .dout_WIDTH( 90 ))
mul_12s_80ns_90_1_1_U1(
    .din0(b_exp_2_fu_1472_p3),
    .din1(Elog2_fu_604_p1),
    .dout(Elog2_fu_604_p2)
);

SABR_mul_13s_71s_71_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 71 ),
    .dout_WIDTH( 71 ))
mul_13s_71s_71_1_1_U2(
    .din0(r_exp_reg_3336),
    .din1(71'd1636647506585939924452),
    .dout(mul_ln568_fu_609_p2)
);

SABR_mul_40ns_40ns_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 40 ),
    .din1_WIDTH( 40 ),
    .dout_WIDTH( 79 ))
mul_40ns_40ns_79_1_1_U3(
    .din0(mul_ln522_fu_614_p0),
    .din1(mul_ln522_fu_614_p1),
    .dout(mul_ln522_fu_614_p2)
);

SABR_mul_43ns_36ns_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 43 ),
    .din1_WIDTH( 36 ),
    .dout_WIDTH( 79 ))
mul_43ns_36ns_79_1_1_U4(
    .din0(mul_ln258_fu_618_p0),
    .din1(mul_ln258_fu_618_p1),
    .dout(mul_ln258_fu_618_p2)
);

SABR_mul_49ns_44ns_93_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 93 ))
mul_49ns_44ns_93_1_1_U5(
    .din0(mul_ln277_fu_622_p0),
    .din1(mul_ln277_fu_622_p1),
    .dout(mul_ln277_fu_622_p2)
);

SABR_mul_50ns_50ns_99_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 99 ))
mul_50ns_50ns_99_1_1_U6(
    .din0(mul_ln616_fu_626_p0),
    .din1(mul_ln616_fu_626_p1),
    .dout(mul_ln616_fu_626_p2)
);

SABR_mul_54s_6ns_54_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 54 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 54 ))
mul_54s_6ns_54_1_1_U7(
    .din0(mul_ln516_fu_630_p0),
    .din1(mul_ln516_fu_630_p1),
    .dout(mul_ln516_fu_630_p2)
);

SABR_mul_73ns_6ns_79_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 73 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 79 ))
mul_73ns_6ns_79_1_1_U8(
    .din0(mul_ln44_1_fu_634_p0),
    .din1(mul_ln44_1_fu_634_p1),
    .dout(mul_ln44_1_fu_634_p2)
);

SABR_mul_77ns_6ns_82_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 77 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 82 ))
mul_77ns_6ns_82_1_1_U9(
    .din0(mul_ln44_6_fu_638_p0),
    .din1(mul_ln44_6_fu_638_p1),
    .dout(mul_ln44_6_fu_638_p2)
);

SABR_mul_78s_54s_131_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 78 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 131 ))
mul_78s_54s_131_1_1_U10(
    .din0(log_base_reg_3213),
    .din1(e_frac_2_fu_2036_p3),
    .dout(m_frac_l_fu_642_p2)
);

SABR_mul_82ns_6ns_87_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 82 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 87 ))
mul_82ns_6ns_87_1_1_U11(
    .din0(mul_ln44_5_fu_646_p0),
    .din1(mul_ln44_5_fu_646_p1),
    .dout(mul_ln44_5_fu_646_p2)
);

SABR_mul_83ns_6ns_89_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 83 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 89 ))
mul_83ns_6ns_89_1_1_U12(
    .din0(mul_ln44_2_fu_650_p0),
    .din1(mul_ln44_2_fu_650_p1),
    .dout(mul_ln44_2_fu_650_p2)
);

SABR_mul_87ns_6ns_92_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 87 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 92 ))
mul_87ns_6ns_92_1_1_U13(
    .din0(mul_ln44_4_fu_654_p0),
    .din1(mul_ln44_4_fu_654_p1),
    .dout(mul_ln44_4_fu_654_p2)
);

SABR_mul_92ns_6ns_97_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 92 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 97 ))
mul_92ns_6ns_97_1_1_U14(
    .din0(mul_ln44_3_fu_658_p0),
    .din1(mul_ln44_3_fu_658_p1),
    .dout(mul_ln44_3_fu_658_p2)
);

SABR_mul_71ns_4ns_75_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 71 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 75 ))
mul_71ns_4ns_75_1_1_U15(
    .din0(mul_ln44_fu_843_p0),
    .din1(mul_ln44_fu_843_p1),
    .dout(mul_ln44_fu_843_p2)
);

(* dissolve_hierarchy = "yes" *) SABR_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U16(
    .din0(1'd1),
    .din1(y_is_int_fu_1829_p4),
    .din2(1'd0),
    .def(y_is_int_fu_1829_p7),
    .sel(y_is_int_fu_1829_p8),
    .dout(y_is_int_fu_1829_p9)
);

SABR_bitselect_1ns_52ns_32s_1_1_1 #(
    .DATAWIDTH( 52 ),
    .ADDRWIDTH( 32 ))
bitselect_1ns_52ns_32s_1_1_1_U17(
    .din(es_sig_fu_1669_p1),
    .sel(y_is_odd_fu_1930_p2),
    .dout(y_is_odd_fu_1930_p3)
);

(* dissolve_hierarchy = "yes" *) SABR_sparsemux_7_2_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 1 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
sparsemux_7_2_1_1_1_U18(
    .din0(1'd1),
    .din1(y_is_odd_reg_3265),
    .din2(1'd0),
    .def(y_is_odd_1_fu_2102_p7),
    .sel(y_is_odd_1_fu_2102_p8),
    .dout(y_is_odd_1_fu_2102_p9)
);

(* dissolve_hierarchy = "yes" *) SABR_sparsemux_19_8_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h80 ),
    .din0_WIDTH( 64 ),
    .CASE1( 8'h40 ),
    .din1_WIDTH( 64 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 64 ),
    .CASE3( 8'h10 ),
    .din3_WIDTH( 64 ),
    .CASE4( 8'h8 ),
    .din4_WIDTH( 64 ),
    .CASE5( 8'h4 ),
    .din5_WIDTH( 64 ),
    .CASE6( 8'h2 ),
    .din6_WIDTH( 64 ),
    .CASE7( 8'h1 ),
    .din7_WIDTH( 64 ),
    .CASE8( 8'h0 ),
    .din8_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 64 ))
sparsemux_19_8_64_1_1_U19(
    .din0(64'd4607182418800017408),
    .din1(retval_2_fu_2905_p4),
    .din2(64'd9223372036854775807),
    .din3(bitcast_ln497_1_fu_2748_p1),
    .din4(bitcast_ln497_2_fu_2759_p1),
    .din5(bitcast_ln497_2_fu_2759_p1),
    .din6(bitcast_ln497_1_fu_2748_p1),
    .din7(bitcast_ln497_2_fu_2759_p1),
    .din8(retval_2_fu_2905_p18),
    .def(retval_2_fu_2905_p19),
    .sel(retval_2_fu_2905_p20),
    .dout(retval_2_fu_2905_p21)
);

SABR_mac_muladd_16s_15ns_19s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15ns_19s_31_4_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m_fix_hi_fu_2275_p4),
    .din1(grp_fu_2949_p1),
    .din2(shl_ln3_fu_2306_p3),
    .ce(grp_fu_2949_ce),
    .dout(grp_fu_2949_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        Z2_reg_3348 <= {{sub_ln574_fu_2378_p2[50:43]}};
        Z2_reg_3348_pp0_iter16_reg <= Z2_reg_3348;
        Z3_reg_3355 <= {{sub_ln574_fu_2378_p2[42:35]}};
        Z4_reg_3360 <= Z4_fu_2413_p1;
        a_1_reg_3042 <= {{sub_ln44_fu_853_p2[75:70]}};
        a_1_reg_3042_pp0_iter3_reg <= a_1_reg_3042;
        a_1_reg_3042_pp0_iter4_reg <= a_1_reg_3042_pp0_iter3_reg;
        a_1_reg_3042_pp0_iter5_reg <= a_1_reg_3042_pp0_iter4_reg;
        a_1_reg_3042_pp0_iter6_reg <= a_1_reg_3042_pp0_iter5_reg;
        a_1_reg_3042_pp0_iter7_reg <= a_1_reg_3042_pp0_iter6_reg;
        a_2_reg_3058 <= {{sub_ln44_1_fu_941_p2[81:76]}};
        a_2_reg_3058_pp0_iter4_reg <= a_2_reg_3058;
        a_2_reg_3058_pp0_iter5_reg <= a_2_reg_3058_pp0_iter4_reg;
        a_2_reg_3058_pp0_iter6_reg <= a_2_reg_3058_pp0_iter5_reg;
        a_2_reg_3058_pp0_iter7_reg <= a_2_reg_3058_pp0_iter6_reg;
        a_reg_3020_pp0_iter2_reg <= a_reg_3020;
        a_reg_3020_pp0_iter3_reg <= a_reg_3020_pp0_iter2_reg;
        a_reg_3020_pp0_iter4_reg <= a_reg_3020_pp0_iter3_reg;
        a_reg_3020_pp0_iter5_reg <= a_reg_3020_pp0_iter4_reg;
        a_reg_3020_pp0_iter6_reg <= a_reg_3020_pp0_iter5_reg;
        a_reg_3020_pp0_iter7_reg <= a_reg_3020_pp0_iter6_reg;
        add_ln261_reg_3380 <= add_ln261_fu_2493_p2;
        bs_exp_reg_2965_pp0_iter2_reg <= bs_exp_reg_2965_pp0_iter1_reg;
        bs_exp_reg_2965_pp0_iter3_reg <= bs_exp_reg_2965_pp0_iter2_reg;
        bs_exp_reg_2965_pp0_iter4_reg <= bs_exp_reg_2965_pp0_iter3_reg;
        bs_exp_reg_2965_pp0_iter5_reg <= bs_exp_reg_2965_pp0_iter4_reg;
        bs_exp_reg_2965_pp0_iter6_reg <= bs_exp_reg_2965_pp0_iter5_reg;
        bs_exp_reg_2965_pp0_iter7_reg <= bs_exp_reg_2965_pp0_iter6_reg;
        bs_exp_reg_2965_pp0_iter8_reg <= bs_exp_reg_2965_pp0_iter7_reg;
        es_exp_reg_3218 <= {{data_1_fu_1650_p1[62:52]}};
        exp_Z1P_m_1_reg_3395 <= {{exp_Z1P_m_1_l_fu_2587_p2[51:2]}};
        exp_Z3_m_1_reg_3375[25 : 0] <= exp_Z3_m_1_fu_2460_p4[25 : 0];
exp_Z3_m_1_reg_3375[42 : 35] <= exp_Z3_m_1_fu_2460_p4[42 : 35];
        exp_read_reg_2960_pp0_iter2_reg <= exp_read_reg_2960_pp0_iter1_reg;
        exp_read_reg_2960_pp0_iter3_reg <= exp_read_reg_2960_pp0_iter2_reg;
        exp_read_reg_2960_pp0_iter4_reg <= exp_read_reg_2960_pp0_iter3_reg;
        exp_read_reg_2960_pp0_iter5_reg <= exp_read_reg_2960_pp0_iter4_reg;
        exp_read_reg_2960_pp0_iter6_reg <= exp_read_reg_2960_pp0_iter5_reg;
        exp_read_reg_2960_pp0_iter7_reg <= exp_read_reg_2960_pp0_iter6_reg;
        exp_read_reg_2960_pp0_iter8_reg <= exp_read_reg_2960_pp0_iter7_reg;
        exp_read_reg_2960_pp0_iter9_reg <= exp_read_reg_2960_pp0_iter8_reg;
        icmp_ln18_3_reg_3193 <= icmp_ln18_3_fu_1448_p2;
        icmp_ln18_4_reg_3009_pp0_iter2_reg <= icmp_ln18_4_reg_3009;
        icmp_ln18_4_reg_3009_pp0_iter3_reg <= icmp_ln18_4_reg_3009_pp0_iter2_reg;
        icmp_ln18_4_reg_3009_pp0_iter4_reg <= icmp_ln18_4_reg_3009_pp0_iter3_reg;
        icmp_ln18_4_reg_3009_pp0_iter5_reg <= icmp_ln18_4_reg_3009_pp0_iter4_reg;
        icmp_ln18_4_reg_3009_pp0_iter6_reg <= icmp_ln18_4_reg_3009_pp0_iter5_reg;
        icmp_ln18_4_reg_3009_pp0_iter7_reg <= icmp_ln18_4_reg_3009_pp0_iter6_reg;
        icmp_ln18_4_reg_3009_pp0_iter8_reg <= icmp_ln18_4_reg_3009_pp0_iter7_reg;
        icmp_ln18_4_reg_3009_pp0_iter9_reg <= icmp_ln18_4_reg_3009_pp0_iter8_reg;
        icmp_ln340_1_reg_3003_pp0_iter2_reg <= icmp_ln340_1_reg_3003;
        icmp_ln340_1_reg_3003_pp0_iter3_reg <= icmp_ln340_1_reg_3003_pp0_iter2_reg;
        icmp_ln340_1_reg_3003_pp0_iter4_reg <= icmp_ln340_1_reg_3003_pp0_iter3_reg;
        icmp_ln340_1_reg_3003_pp0_iter5_reg <= icmp_ln340_1_reg_3003_pp0_iter4_reg;
        icmp_ln340_1_reg_3003_pp0_iter6_reg <= icmp_ln340_1_reg_3003_pp0_iter5_reg;
        icmp_ln340_1_reg_3003_pp0_iter7_reg <= icmp_ln340_1_reg_3003_pp0_iter6_reg;
        icmp_ln340_1_reg_3003_pp0_iter8_reg <= icmp_ln340_1_reg_3003_pp0_iter7_reg;
        icmp_ln340_1_reg_3003_pp0_iter9_reg <= icmp_ln340_1_reg_3003_pp0_iter8_reg;
        icmp_ln422_reg_3298 <= icmp_ln422_fu_2066_p2;
        icmp_ln422_reg_3298_pp0_iter12_reg <= icmp_ln422_reg_3298;
        icmp_ln422_reg_3298_pp0_iter13_reg <= icmp_ln422_reg_3298_pp0_iter12_reg;
        icmp_ln422_reg_3298_pp0_iter14_reg <= icmp_ln422_reg_3298_pp0_iter13_reg;
        icmp_ln422_reg_3298_pp0_iter15_reg <= icmp_ln422_reg_3298_pp0_iter14_reg;
        icmp_ln422_reg_3298_pp0_iter16_reg <= icmp_ln422_reg_3298_pp0_iter15_reg;
        icmp_ln422_reg_3298_pp0_iter17_reg <= icmp_ln422_reg_3298_pp0_iter16_reg;
        icmp_ln422_reg_3298_pp0_iter18_reg <= icmp_ln422_reg_3298_pp0_iter17_reg;
        icmp_ln628_1_reg_3400 <= icmp_ln628_1_fu_2676_p2;
        icmp_ln628_reg_3326 <= icmp_ln628_fu_2301_p2;
        icmp_ln628_reg_3326_pp0_iter12_reg <= icmp_ln628_reg_3326;
        icmp_ln628_reg_3326_pp0_iter13_reg <= icmp_ln628_reg_3326_pp0_iter12_reg;
        icmp_ln628_reg_3326_pp0_iter14_reg <= icmp_ln628_reg_3326_pp0_iter13_reg;
        icmp_ln628_reg_3326_pp0_iter15_reg <= icmp_ln628_reg_3326_pp0_iter14_reg;
        icmp_ln628_reg_3326_pp0_iter16_reg <= icmp_ln628_reg_3326_pp0_iter15_reg;
        icmp_ln628_reg_3326_pp0_iter17_reg <= icmp_ln628_reg_3326_pp0_iter16_reg;
        icmp_ln628_reg_3326_pp0_iter18_reg <= icmp_ln628_reg_3326_pp0_iter17_reg;
        icmp_ln645_reg_3405 <= icmp_ln645_fu_2682_p2;
        log_base_reg_3213 <= {{add_ln525_1_fu_1634_p2[120:43]}};
        m_diff_hi_reg_3343 <= {{sub_ln574_fu_2378_p2[58:51]}};
        m_diff_hi_reg_3343_pp0_iter16_reg <= m_diff_hi_reg_3343;
        m_exp_reg_3223 <= m_exp_fu_1677_p2;
        m_fix_reg_3311 <= {{m_fix_0_in_in_v_v_fu_2250_p3[117:59]}};
        m_fix_reg_3311_pp0_iter12_reg <= m_fix_reg_3311;
        m_fix_reg_3311_pp0_iter13_reg <= m_fix_reg_3311_pp0_iter12_reg;
        m_fix_reg_3311_pp0_iter14_reg <= m_fix_reg_3311_pp0_iter13_reg;
        m_frac_l_reg_3282 <= m_frac_l_fu_642_p2;
        or_ln378_1_reg_3252 <= or_ln378_1_fu_1861_p2;
        or_ln378_1_reg_3252_pp0_iter11_reg <= or_ln378_1_reg_3252;
        or_ln378_1_reg_3252_pp0_iter12_reg <= or_ln378_1_reg_3252_pp0_iter11_reg;
        or_ln378_1_reg_3252_pp0_iter13_reg <= or_ln378_1_reg_3252_pp0_iter12_reg;
        or_ln378_1_reg_3252_pp0_iter14_reg <= or_ln378_1_reg_3252_pp0_iter13_reg;
        or_ln378_1_reg_3252_pp0_iter15_reg <= or_ln378_1_reg_3252_pp0_iter14_reg;
        or_ln378_1_reg_3252_pp0_iter16_reg <= or_ln378_1_reg_3252_pp0_iter15_reg;
        or_ln378_1_reg_3252_pp0_iter17_reg <= or_ln378_1_reg_3252_pp0_iter16_reg;
        or_ln378_1_reg_3252_pp0_iter18_reg <= or_ln378_1_reg_3252_pp0_iter17_reg;
        or_ln386_2_reg_3259 <= or_ln386_2_fu_1891_p2;
        or_ln386_2_reg_3259_pp0_iter11_reg <= or_ln386_2_reg_3259;
        or_ln386_2_reg_3259_pp0_iter12_reg <= or_ln386_2_reg_3259_pp0_iter11_reg;
        or_ln386_2_reg_3259_pp0_iter13_reg <= or_ln386_2_reg_3259_pp0_iter12_reg;
        or_ln386_2_reg_3259_pp0_iter14_reg <= or_ln386_2_reg_3259_pp0_iter13_reg;
        or_ln386_2_reg_3259_pp0_iter15_reg <= or_ln386_2_reg_3259_pp0_iter14_reg;
        or_ln386_2_reg_3259_pp0_iter16_reg <= or_ln386_2_reg_3259_pp0_iter15_reg;
        or_ln386_2_reg_3259_pp0_iter17_reg <= or_ln386_2_reg_3259_pp0_iter16_reg;
        or_ln386_2_reg_3259_pp0_iter18_reg <= or_ln386_2_reg_3259_pp0_iter17_reg;
        or_ln431_2_reg_3270 <= or_ln431_2_fu_1972_p2;
        or_ln431_2_reg_3270_pp0_iter11_reg <= or_ln431_2_reg_3270;
        or_ln431_2_reg_3270_pp0_iter12_reg <= or_ln431_2_reg_3270_pp0_iter11_reg;
        or_ln431_2_reg_3270_pp0_iter13_reg <= or_ln431_2_reg_3270_pp0_iter12_reg;
        or_ln431_2_reg_3270_pp0_iter14_reg <= or_ln431_2_reg_3270_pp0_iter13_reg;
        or_ln431_2_reg_3270_pp0_iter15_reg <= or_ln431_2_reg_3270_pp0_iter14_reg;
        or_ln431_2_reg_3270_pp0_iter16_reg <= or_ln431_2_reg_3270_pp0_iter15_reg;
        or_ln431_2_reg_3270_pp0_iter17_reg <= or_ln431_2_reg_3270_pp0_iter16_reg;
        or_ln431_2_reg_3270_pp0_iter18_reg <= or_ln431_2_reg_3270_pp0_iter17_reg;
        or_ln438_2_reg_3276 <= or_ln438_2_fu_2012_p2;
        or_ln438_2_reg_3276_pp0_iter11_reg <= or_ln438_2_reg_3276;
        or_ln438_2_reg_3276_pp0_iter12_reg <= or_ln438_2_reg_3276_pp0_iter11_reg;
        or_ln438_2_reg_3276_pp0_iter13_reg <= or_ln438_2_reg_3276_pp0_iter12_reg;
        or_ln438_2_reg_3276_pp0_iter14_reg <= or_ln438_2_reg_3276_pp0_iter13_reg;
        or_ln438_2_reg_3276_pp0_iter15_reg <= or_ln438_2_reg_3276_pp0_iter14_reg;
        or_ln438_2_reg_3276_pp0_iter16_reg <= or_ln438_2_reg_3276_pp0_iter15_reg;
        or_ln438_2_reg_3276_pp0_iter17_reg <= or_ln438_2_reg_3276_pp0_iter16_reg;
        or_ln438_2_reg_3276_pp0_iter18_reg <= or_ln438_2_reg_3276_pp0_iter17_reg;
        out_sig_reg_3410 <= out_sig_fu_2708_p3;
        r_exp_reg_3336 <= r_exp_fu_2356_p3;
        r_exp_reg_3336_pp0_iter15_reg <= r_exp_reg_3336;
        r_exp_reg_3336_pp0_iter16_reg <= r_exp_reg_3336_pp0_iter15_reg;
        r_exp_reg_3336_pp0_iter17_reg <= r_exp_reg_3336_pp0_iter16_reg;
        r_sign_reg_3303 <= r_sign_fu_2121_p2;
        r_sign_reg_3303_pp0_iter12_reg <= r_sign_reg_3303;
        r_sign_reg_3303_pp0_iter13_reg <= r_sign_reg_3303_pp0_iter12_reg;
        r_sign_reg_3303_pp0_iter14_reg <= r_sign_reg_3303_pp0_iter13_reg;
        r_sign_reg_3303_pp0_iter15_reg <= r_sign_reg_3303_pp0_iter14_reg;
        r_sign_reg_3303_pp0_iter16_reg <= r_sign_reg_3303_pp0_iter15_reg;
        r_sign_reg_3303_pp0_iter17_reg <= r_sign_reg_3303_pp0_iter16_reg;
        r_sign_reg_3303_pp0_iter18_reg <= r_sign_reg_3303_pp0_iter17_reg;
        sub_ln44_1_reg_3053 <= sub_ln44_1_fu_941_p2;
        tmp_10_reg_3086 <= {{sub_ln44_3_fu_1110_p2[120:34]}};
        tmp_11_reg_3092 <= {{sub_ln44_3_fu_1110_p2[114:34]}};
        tmp_13_reg_3097 <= {{sub_ln44_3_fu_1110_p2[120:115]}};
        tmp_13_reg_3097_pp0_iter6_reg <= tmp_13_reg_3097;
        tmp_13_reg_3097_pp0_iter7_reg <= tmp_13_reg_3097_pp0_iter6_reg;
        tmp_14_reg_3103 <= {{sub_ln44_4_fu_1198_p2[125:44]}};
        tmp_15_reg_3109 <= {{sub_ln44_4_fu_1198_p2[119:44]}};
        tmp_16_reg_3114 <= {{sub_ln44_4_fu_1198_p2[125:120]}};
        tmp_16_reg_3114_pp0_iter7_reg <= tmp_16_reg_3114;
        tmp_17_reg_3120 <= {{sub_ln44_5_fu_1286_p2[130:54]}};
        tmp_18_reg_3126 <= {{sub_ln44_5_fu_1286_p2[124:54]}};
        tmp_19_reg_3131 <= {{sub_ln44_5_fu_1286_p2[130:125]}};
        tmp_1_reg_3244 <= m_exp_fu_1677_p2[32'd11];
        tmp_20_reg_3177 <= {{sub_ln44_6_fu_1398_p2[135:64]}};
        tmp_21_reg_3182 <= {{sub_ln44_6_fu_1398_p2[135:96]}};
        tmp_23_reg_3316 <= zext_ln549_fu_2261_p1[32'd129];
        tmp_23_reg_3316_pp0_iter12_reg <= tmp_23_reg_3316;
        tmp_2_reg_3206 <= b_exp_fu_1431_p2[32'd11];
        tmp_30_reg_3292 <= m_frac_l_fu_642_p2[32'd130];
        tmp_30_reg_3292_pp0_iter11_reg <= tmp_30_reg_3292;
        tmp_30_reg_3292_pp0_iter12_reg <= tmp_30_reg_3292_pp0_iter11_reg;
        tmp_30_reg_3292_pp0_iter13_reg <= tmp_30_reg_3292_pp0_iter12_reg;
        tmp_30_reg_3292_pp0_iter14_reg <= tmp_30_reg_3292_pp0_iter13_reg;
        tmp_30_reg_3292_pp0_iter15_reg <= tmp_30_reg_3292_pp0_iter14_reg;
        tmp_30_reg_3292_pp0_iter16_reg <= tmp_30_reg_3292_pp0_iter15_reg;
        tmp_30_reg_3292_pp0_iter17_reg <= tmp_30_reg_3292_pp0_iter16_reg;
        tmp_30_reg_3292_pp0_iter18_reg <= tmp_30_reg_3292_pp0_iter17_reg;
        tmp_5_reg_2987_pp0_iter2_reg <= tmp_5_reg_2987_pp0_iter1_reg;
        tmp_5_reg_2987_pp0_iter3_reg <= tmp_5_reg_2987_pp0_iter2_reg;
        tmp_5_reg_2987_pp0_iter4_reg <= tmp_5_reg_2987_pp0_iter3_reg;
        tmp_5_reg_2987_pp0_iter5_reg <= tmp_5_reg_2987_pp0_iter4_reg;
        tmp_5_reg_2987_pp0_iter6_reg <= tmp_5_reg_2987_pp0_iter5_reg;
        tmp_5_reg_2987_pp0_iter7_reg <= tmp_5_reg_2987_pp0_iter6_reg;
        tmp_5_reg_2987_pp0_iter8_reg <= tmp_5_reg_2987_pp0_iter7_reg;
        tmp_7_reg_3048 <= {{sub_ln44_fu_853_p2[69:3]}};
        tmp_8_reg_3075 <= {{sub_ln44_2_fu_1022_p2[95:10]}};
        tmp_9_reg_3080 <= {{sub_ln44_2_fu_1022_p2[101:96]}};
        tmp_9_reg_3080_pp0_iter5_reg <= tmp_9_reg_3080;
        tmp_9_reg_3080_pp0_iter6_reg <= tmp_9_reg_3080_pp0_iter5_reg;
        tmp_9_reg_3080_pp0_iter7_reg <= tmp_9_reg_3080_pp0_iter6_reg;
        tmp_reg_2980_pp0_iter2_reg <= tmp_reg_2980_pp0_iter1_reg;
        tmp_reg_2980_pp0_iter3_reg <= tmp_reg_2980_pp0_iter2_reg;
        tmp_reg_2980_pp0_iter4_reg <= tmp_reg_2980_pp0_iter3_reg;
        tmp_reg_2980_pp0_iter5_reg <= tmp_reg_2980_pp0_iter4_reg;
        tmp_reg_2980_pp0_iter6_reg <= tmp_reg_2980_pp0_iter5_reg;
        tmp_reg_2980_pp0_iter7_reg <= tmp_reg_2980_pp0_iter6_reg;
        tmp_reg_2980_pp0_iter8_reg <= tmp_reg_2980_pp0_iter7_reg;
        tmp_reg_2980_pp0_iter9_reg <= tmp_reg_2980_pp0_iter8_reg;
        trunc_ln39_1_reg_3064 <= trunc_ln39_1_fu_957_p1;
        trunc_ln657_reg_3415 <= trunc_ln657_fu_2716_p1;
        x_is_0_reg_3199 <= x_is_0_fu_1453_p2;
        x_is_1_reg_3187 <= x_is_1_fu_1443_p2;
        x_is_n1_reg_3233 <= x_is_n1_fu_1699_p2;
        x_is_n1_reg_3233_pp0_iter11_reg <= x_is_n1_reg_3233;
        x_is_n1_reg_3233_pp0_iter12_reg <= x_is_n1_reg_3233_pp0_iter11_reg;
        x_is_n1_reg_3233_pp0_iter13_reg <= x_is_n1_reg_3233_pp0_iter12_reg;
        x_is_n1_reg_3233_pp0_iter14_reg <= x_is_n1_reg_3233_pp0_iter13_reg;
        x_is_n1_reg_3233_pp0_iter15_reg <= x_is_n1_reg_3233_pp0_iter14_reg;
        x_is_n1_reg_3233_pp0_iter16_reg <= x_is_n1_reg_3233_pp0_iter15_reg;
        x_is_n1_reg_3233_pp0_iter17_reg <= x_is_n1_reg_3233_pp0_iter16_reg;
        x_is_n1_reg_3233_pp0_iter18_reg <= x_is_n1_reg_3233_pp0_iter17_reg;
        x_is_neg_reg_3239 <= x_is_neg_fu_1752_p2;
        y_is_odd_reg_3265 <= y_is_odd_fu_1930_p3;
        z2_reg_3036 <= {{sub_ln44_fu_853_p2[75:3]}};
        z4_reg_3069 <= {{sub_ln44_2_fu_1022_p2[101:10]}};
        zext_ln502_reg_2993_pp0_iter2_reg[5 : 0] <= zext_ln502_reg_2993_pp0_iter1_reg[5 : 0];
        zext_ln502_reg_2993_pp0_iter3_reg[5 : 0] <= zext_ln502_reg_2993_pp0_iter2_reg[5 : 0];
        zext_ln502_reg_2993_pp0_iter4_reg[5 : 0] <= zext_ln502_reg_2993_pp0_iter3_reg[5 : 0];
        zext_ln502_reg_2993_pp0_iter5_reg[5 : 0] <= zext_ln502_reg_2993_pp0_iter4_reg[5 : 0];
        zext_ln502_reg_2993_pp0_iter6_reg[5 : 0] <= zext_ln502_reg_2993_pp0_iter5_reg[5 : 0];
        zext_ln502_reg_2993_pp0_iter7_reg[5 : 0] <= zext_ln502_reg_2993_pp0_iter6_reg[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_reg_3020 <= {{mul_ln516_fu_630_p2[53:50]}};
        bs_exp_reg_2965 <= {{data_fu_662_p1[62:52]}};
        bs_exp_reg_2965_pp0_iter1_reg <= bs_exp_reg_2965;
        bs_sig_reg_2972 <= bs_sig_fu_674_p1;
        exp_read_reg_2960 <= exp;
        exp_read_reg_2960_pp0_iter1_reg <= exp_read_reg_2960;
        icmp_ln18_4_reg_3009 <= icmp_ln18_4_fu_714_p2;
        icmp_ln340_1_reg_3003 <= icmp_ln340_1_fu_709_p2;
        mul_ln516_reg_3014 <= mul_ln516_fu_630_p2;
        tmp_5_reg_2987 <= data_fu_662_p1[32'd51];
        tmp_5_reg_2987_pp0_iter1_reg <= tmp_5_reg_2987;
        tmp_6_reg_3031 <= mul_ln516_fu_630_p2[32'd53];
        tmp_reg_2980 <= data_fu_662_p1[32'd63];
        tmp_reg_2980_pp0_iter1_reg <= tmp_reg_2980;
        trunc_ln39_reg_3026 <= trunc_ln39_fu_762_p1;
        zext_ln502_reg_2993[5 : 0] <= zext_ln502_fu_704_p1[5 : 0];
        zext_ln502_reg_2993_pp0_iter1_reg[5 : 0] <= zext_ln502_reg_2993[5 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter19 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to18 = 1'b1;
    end else begin
        ap_idle_pp0_0to18 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to18 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_2949_ce = 1'b1;
    end else begin
        grp_fu_2949_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter17 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter16 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_ce0_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_ce))) begin
        pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_ce1_local = 1'b1;
    end else begin
        pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Elog2_fu_604_p1 = 90'd418981761686000620659953;

assign Z3_fu_2403_p4 = {{sub_ln574_fu_2378_p2[42:35]}};

assign Z4_fu_2413_p1 = sub_ln574_fu_2378_p2[34:0];

assign Z4_ind_fu_2417_p4 = {{sub_ln574_fu_2378_p2[34:27]}};

assign add_ln209_1_fu_1518_p2 = (zext_ln194_1_fu_1488_p1 + zext_ln194_2_fu_1492_p1);

assign add_ln209_2_fu_1528_p2 = (zext_ln209_fu_1524_p1 + add_ln209_fu_1512_p2);

assign add_ln209_3_fu_1534_p2 = (zext_ln194_3_fu_1496_p1 + zext_ln194_4_fu_1500_p1);

assign add_ln209_4_fu_1540_p2 = (zext_ln194_5_fu_1504_p1 + zext_ln194_6_fu_1508_p1);

assign add_ln209_5_fu_1550_p2 = (zext_ln209_1_fu_1546_p1 + add_ln209_3_fu_1534_p2);

assign add_ln209_fu_1512_p2 = (zext_ln194_fu_1484_p1 + pow_reduce_anonymous_namespace_log0_lut_table_array_q0);

assign add_ln261_fu_2493_p2 = (exp_Z4_m_1_fu_2454_p2 + zext_ln261_1_fu_2489_p1);

assign add_ln280_fu_2577_p2 = (exp_Z2P_m_1_fu_2513_p2 + zext_ln280_2_fu_2573_p1);

assign add_ln373_fu_1781_p2 = (es_exp_cast_fu_1771_p4 + 6'd1);

assign add_ln44_1_fu_915_p2 = (zext_ln44_3_fu_907_p1 + zext_ln44_4_fu_911_p1);

assign add_ln44_2_fu_995_p2 = (zext_ln44_8_fu_987_p1 + zext_ln44_9_fu_991_p1);

assign add_ln44_3_fu_1084_p2 = (zext_ln44_13_fu_1076_p1 + zext_ln44_14_fu_1080_p1);

assign add_ln44_4_fu_1172_p2 = (zext_ln44_18_fu_1164_p1 + zext_ln44_19_fu_1168_p1);

assign add_ln44_5_fu_1260_p2 = (zext_ln44_23_fu_1252_p1 + zext_ln44_24_fu_1256_p1);

assign add_ln44_6_fu_1372_p2 = (zext_ln44_28_fu_1364_p1 + zext_ln44_29_fu_1368_p1);

assign add_ln44_fu_834_p2 = (zext_ln44_fu_830_p1 + select_ln42_fu_816_p3);

assign add_ln525_1_fu_1634_p2 = (add_ln525_fu_1624_p2 + zext_ln525_fu_1630_p1);

assign add_ln525_fu_1624_p2 = ($signed(sext_ln525_fu_1616_p1) + $signed(sext_ln525_1_fu_1620_p1));

assign add_ln563_1_fu_2342_p2 = (tmp_9_cast_fu_2317_p4 + 13'd1);

assign add_ln616_1_fu_2640_p2 = (shl_ln4_fu_2628_p3 + zext_ln616_2_fu_2636_p1);

assign add_ln616_fu_2613_p2 = (pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_q0 + 58'd16);

assign and_ln342_1_fu_2819_p2 = (xor_ln386_1_fu_2793_p2 & xor_ln342_fu_2814_p2);

assign and_ln342_fu_2799_p2 = (xor_ln386_1_fu_2793_p2 & x_is_n1_reg_3233_pp0_iter18_reg);

assign and_ln373_1_fu_1797_p2 = (lshr_ln373_fu_1791_p2 & es_sig_fu_1669_p1);

assign and_ln378_fu_1849_p2 = (y_is_inf_fu_1715_p2 & x_is_n1_fu_1699_p2);

assign and_ln386_1_fu_2809_p2 = (xor_ln386_2_fu_2804_p2 & or_ln386_2_reg_3259_pp0_iter18_reg);

assign and_ln386_fu_1879_p2 = (xor_ln386_fu_1873_p2 & x_is_neg_fu_1752_p2);

assign and_ln422_1_fu_2088_p2 = (icmp_ln422_fu_2066_p2 & and_ln422_fu_2082_p2);

assign and_ln422_fu_2082_p2 = (xor_ln421_fu_2076_p2 & icmp_ln422_1_fu_2071_p2);

assign and_ln431_1_fu_1944_p2 = (y_is_ninf_fu_1909_p2 & tmp_2_reg_3206);

assign and_ln431_2_fu_1949_p2 = (y_is_pos_fu_1897_p2 & x_is_inf_fu_1737_p2);

assign and_ln431_3_fu_1955_p2 = (x_is_0_reg_3199 & es_sign_fu_1653_p3);

assign and_ln431_4_fu_2825_p2 = (or_ln431_2_reg_3270_pp0_iter18_reg & and_ln342_1_fu_2819_p2);

assign and_ln431_5_fu_2830_p2 = (xor_ln431_fu_2731_p2 & and_ln342_1_fu_2819_p2);

assign and_ln431_fu_1938_p2 = (y_is_pinf_fu_1903_p2 & x_abs_greater_1_fu_1915_p2);

assign and_ln438_1_fu_1983_p2 = (y_is_ninf_fu_1909_p2 & x_abs_greater_1_fu_1915_p2);

assign and_ln438_2_fu_1989_p2 = (y_is_pos_fu_1897_p2 & x_is_0_reg_3199);

assign and_ln438_3_fu_1994_p2 = (x_is_inf_fu_1737_p2 & es_sign_fu_1653_p3);

assign and_ln438_4_fu_2836_p2 = (or_ln438_2_reg_3276_pp0_iter18_reg & and_ln431_5_fu_2830_p2);

assign and_ln438_5_fu_2841_p2 = (xor_ln438_fu_2736_p2 & and_ln431_5_fu_2830_p2);

assign and_ln438_fu_1978_p2 = (y_is_pinf_fu_1903_p2 & tmp_2_reg_3206);

assign and_ln628_1_fu_2847_p2 = (or_ln628_fu_2767_p2 & and_ln438_5_fu_2841_p2);

assign and_ln628_fu_2763_p2 = (icmp_ln628_reg_3326_pp0_iter18_reg & icmp_ln422_reg_3298_pp0_iter18_reg);

assign and_ln629_1_fu_2863_p2 = (xor_ln629_fu_2858_p2 & and_ln628_1_fu_2847_p2);

assign and_ln629_fu_2853_p2 = (tmp_30_reg_3292_pp0_iter18_reg & and_ln628_1_fu_2847_p2);

assign and_ln645_1_fu_2880_p2 = (and_ln645_fu_2875_p2 & and_ln438_5_fu_2841_p2);

assign and_ln645_fu_2875_p2 = (xor_ln628_fu_2869_p2 & icmp_ln645_reg_3405);

assign and_ln_fu_2548_p5 = {{{{Z2_reg_3348_pp0_iter16_reg}, {1'd0}}, {tmp_26_fu_2519_p4}}, {2'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = retval_2_fu_2905_p21;

assign ashr_ln545_fu_2149_p2 = $signed(m_frac_l_reg_3282) >>> zext_ln545_fu_2145_p1;

assign ashr_ln546_fu_2184_p2 = $signed(m_fix_l_fu_2167_p3) >>> zext_ln546_fu_2174_p1;

assign ashr_ln553_fu_2237_p2 = $signed(m_frac_l_reg_3282) >>> zext_ln553_fu_2228_p1;

assign b_exp_1_fu_1466_p2 = ($signed(zext_ln486_fu_1428_p1) + $signed(12'd3074));

assign b_exp_2_fu_1472_p3 = ((tmp_5_reg_2987_pp0_iter8_reg[0:0] == 1'b1) ? b_exp_1_fu_1466_p2 : b_exp_fu_1431_p2);

assign b_exp_fu_1431_p2 = ($signed(zext_ln486_fu_1428_p1) + $signed(12'd3073));

assign b_frac_1_fu_728_p3 = {{1'd1}, {bs_sig_reg_2972}};

assign b_frac_fu_719_p4 = {{{{1'd1}, {bs_sig_reg_2972}}}, {1'd0}};

assign bitcast_ln497_1_fu_2748_p1 = t_1_fu_2741_p3;

assign bitcast_ln497_2_fu_2759_p1 = t_2_fu_2752_p3;

assign bs_sig_fu_674_p1 = data_fu_662_p1[51:0];

assign data_1_fu_1650_p1 = exp_read_reg_2960_pp0_iter9_reg;

assign data_fu_662_p1 = base_r;

assign eZ_1_fu_972_p3 = {{1'd1}, {zext_ln40_1_fu_968_p1}};

assign eZ_2_fu_1061_p3 = {{1'd1}, {zext_ln40_2_fu_1058_p1}};

assign eZ_3_fu_1149_p3 = {{1'd1}, {zext_ln40_3_fu_1146_p1}};

assign eZ_4_fu_1237_p3 = {{1'd1}, {zext_ln40_4_fu_1234_p1}};

assign eZ_5_fu_1349_p3 = {{1'd1}, {zext_ln40_5_fu_1346_p1}};

assign eZ_fu_892_p3 = {{1'd1}, {zext_ln40_fu_889_p1}};

assign e_frac_1_fu_2030_p2 = (54'd0 - zext_ln532_fu_2026_p1);

assign e_frac_2_fu_2036_p3 = ((es_sign_fu_1653_p3[0:0] == 1'b1) ? e_frac_1_fu_2030_p2 : zext_ln532_fu_2026_p1);

assign e_frac_fu_2018_p3 = {{1'd1}, {es_sig_fu_1669_p1}};

assign empty_fu_2257_p1 = m_fix_0_in_in_v_v_fu_2250_p3[129:0];

assign es_exp_cast_fu_1771_p4 = {{data_1_fu_1650_p1[57:52]}};

assign es_exp_fu_1661_p3 = {{data_1_fu_1650_p1[62:52]}};

assign es_sig_fu_1669_p1 = data_1_fu_1650_p1[51:0];

assign es_sign_fu_1653_p3 = data_1_fu_1650_p1[32'd63];

assign exp_Z1P_m_1_l_fu_2587_p2 = (zext_ln280_1_fu_2583_p1 + zext_ln280_fu_2559_p1);

assign exp_Z1_hi_fu_2603_p4 = {{pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_q0[57:8]}};

assign exp_Z2P_m_1_fu_2513_p2 = (zext_ln261_fu_2510_p1 + zext_ln255_fu_2507_p1);

assign exp_Z2_m_1_fu_2529_p4 = {{{Z2_reg_3348_pp0_iter16_reg}, {1'd0}}, {tmp_26_fu_2519_p4}};

assign exp_Z3_m_1_fu_2460_p4 = {{{Z3_reg_3355}, {9'd0}}, {pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_q0}};

assign exp_Z4_m_1_fu_2454_p2 = (zext_ln250_fu_2447_p1 + zext_ln250_1_fu_2450_p1);

assign f_Z4_fu_2437_p4 = {{pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_q1[25:16]}};

assign grp_fu_2949_p1 = 31'd23637;

assign icmp_ln18_1_fu_1709_p2 = ((es_sig_fu_1669_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_2_fu_1721_p2 = ((es_sig_fu_1669_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_3_fu_1448_p2 = ((bs_exp_reg_2965_pp0_iter8_reg == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln18_4_fu_714_p2 = ((bs_sig_reg_2972 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_1703_p2 = ((es_exp_fu_1661_p3 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln340_1_fu_709_p2 = ((bs_sig_reg_2972 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln340_fu_1437_p2 = ((b_exp_fu_1431_p2 == 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln372_fu_1757_p2 = (($signed(m_exp_fu_1677_p2) > $signed(12'd51)) ? 1'b1 : 1'b0);

assign icmp_ln421_fu_2061_p2 = ((m_exp_reg_3223 == 12'd0) ? 1'b1 : 1'b0);

assign icmp_ln422_1_fu_2071_p2 = (($signed(m_exp_reg_3223) < $signed(12'd53)) ? 1'b1 : 1'b0);

assign icmp_ln422_fu_2066_p2 = (($signed(m_exp_reg_3223) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln563_fu_2336_p2 = ((trunc_ln563_fu_2333_p1 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln628_1_fu_2676_p2 = (($signed(tmp_29_fu_2666_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln628_fu_2301_p2 = ((m_frac_l_reg_3282 != sext_ln628_fu_2297_p1) ? 1'b1 : 1'b0);

assign icmp_ln645_fu_2682_p2 = (($signed(r_exp_2_fu_2659_p3) < $signed(13'd7170)) ? 1'b1 : 1'b0);

assign index0_fu_694_p4 = {{data_fu_662_p1[51:46]}};

assign log_sum_1_fu_1560_p2 = (zext_ln209_2_fu_1556_p1 + add_ln209_2_fu_1528_p2);

assign lshr_ln373_fu_1791_p2 = 52'd4503599627370495 >> zext_ln373_fu_1787_p1;

assign lshr_ln522_1_fu_1598_p4 = {{sub_ln522_fu_1592_p2[116:45]}};

assign lshr_ln_fu_1571_p4 = {{mul_ln522_fu_614_p2[78:1]}};

assign m_exp_fu_1677_p2 = ($signed(zext_ln486_1_fu_1673_p1) + $signed(12'd3073));

assign m_fix_0_in_in_v_v_fu_2250_p3 = ((tmp_1_reg_3244[0:0] == 1'b1) ? select_ln553_1_fu_2242_p3 : shl_ln552_fu_2204_p2);

assign m_fix_a_fu_2368_p4 = {{mul_ln568_fu_609_p2[70:12]}};

assign m_fix_back_fu_2190_p3 = ((tmp_1_reg_3244[0:0] == 1'b1) ? shl_ln546_fu_2178_p2 : ashr_ln546_fu_2184_p2);

assign m_fix_hi_fu_2275_p4 = {{m_fix_0_in_in_v_v_fu_2250_p3[129:114]}};

assign m_fix_l_fu_2167_p3 = ((tmp_1_reg_3244[0:0] == 1'b1) ? trunc_ln545_fu_2159_p1 : trunc_ln545_1_fu_2163_p1);

assign mul_ln258_fu_618_p0 = mul_ln258_fu_618_p00;

assign mul_ln258_fu_618_p00 = exp_Z3_m_1_fu_2460_p4;

assign mul_ln258_fu_618_p1 = mul_ln258_fu_618_p10;

assign mul_ln258_fu_618_p10 = exp_Z4_m_1_fu_2454_p2;

assign mul_ln277_fu_622_p0 = mul_ln277_fu_622_p00;

assign mul_ln277_fu_622_p00 = exp_Z2_m_1_fu_2529_p4;

assign mul_ln277_fu_622_p1 = mul_ln277_fu_622_p10;

assign mul_ln277_fu_622_p10 = exp_Z2P_m_1_fu_2513_p2;

assign mul_ln44_1_fu_634_p0 = mul_ln44_1_fu_634_p00;

assign mul_ln44_1_fu_634_p00 = z2_reg_3036;

assign mul_ln44_1_fu_634_p1 = mul_ln44_1_fu_634_p10;

assign mul_ln44_1_fu_634_p10 = a_1_reg_3042;

assign mul_ln44_2_fu_650_p0 = mul_ln44_2_fu_650_p00;

assign mul_ln44_2_fu_650_p00 = z3_fu_961_p3;

assign mul_ln44_2_fu_650_p1 = mul_ln44_2_fu_650_p10;

assign mul_ln44_2_fu_650_p10 = a_2_reg_3058;

assign mul_ln44_3_fu_658_p0 = mul_ln44_3_fu_658_p00;

assign mul_ln44_3_fu_658_p00 = z4_reg_3069;

assign mul_ln44_3_fu_658_p1 = mul_ln44_3_fu_658_p10;

assign mul_ln44_3_fu_658_p10 = tmp_9_reg_3080;

assign mul_ln44_4_fu_654_p0 = mul_ln44_4_fu_654_p00;

assign mul_ln44_4_fu_654_p00 = tmp_10_reg_3086;

assign mul_ln44_4_fu_654_p1 = mul_ln44_4_fu_654_p10;

assign mul_ln44_4_fu_654_p10 = tmp_13_reg_3097;

assign mul_ln44_5_fu_646_p0 = mul_ln44_5_fu_646_p00;

assign mul_ln44_5_fu_646_p00 = tmp_14_reg_3103;

assign mul_ln44_5_fu_646_p1 = mul_ln44_5_fu_646_p10;

assign mul_ln44_5_fu_646_p10 = tmp_16_reg_3114;

assign mul_ln44_6_fu_638_p0 = mul_ln44_6_fu_638_p00;

assign mul_ln44_6_fu_638_p00 = tmp_17_reg_3120;

assign mul_ln44_6_fu_638_p1 = mul_ln44_6_fu_638_p10;

assign mul_ln44_6_fu_638_p10 = tmp_19_reg_3131;

assign mul_ln44_fu_843_p0 = zext_ln42_1_fu_800_p1;

assign mul_ln44_fu_843_p1 = mul_ln44_fu_843_p10;

assign mul_ln44_fu_843_p10 = a_reg_3020;

assign mul_ln516_fu_630_p0 = ((tmp_5_reg_2987[0:0] == 1'b1) ? zext_ln485_fu_735_p1 : b_frac_fu_719_p4);

assign mul_ln516_fu_630_p1 = mul_ln516_fu_630_p10;

assign mul_ln516_fu_630_p10 = pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_q0;

assign mul_ln522_fu_614_p0 = zext_ln522_fu_1566_p1;

assign mul_ln522_fu_614_p1 = zext_ln522_fu_1566_p1;

assign mul_ln616_fu_626_p0 = mul_ln616_fu_626_p00;

assign mul_ln616_fu_626_p00 = exp_Z1P_m_1_reg_3395;

assign mul_ln616_fu_626_p1 = mul_ln616_fu_626_p10;

assign mul_ln616_fu_626_p10 = exp_Z1_hi_fu_2603_p4;

assign or_ln357_fu_1741_p2 = (x_is_inf_fu_1737_p2 | x_is_0_reg_3199);

assign or_ln373_fu_1809_p2 = (tmp_1_fu_1763_p3 | icmp_ln372_fu_1757_p2);

assign or_ln378_1_fu_1861_p2 = (y_is_0_fu_1683_p2 | or_ln378_fu_1855_p2);

assign or_ln378_fu_1855_p2 = (x_is_p1_fu_1694_p2 | and_ln378_fu_1849_p2);

assign or_ln386_1_fu_1885_p2 = (x_is_NaN_fu_1733_p2 | and_ln386_fu_1879_p2);

assign or_ln386_2_fu_1891_p2 = (y_is_NaN_fu_1727_p2 | or_ln386_1_fu_1885_p2);

assign or_ln386_3_fu_2789_p2 = (or_ln386_2_reg_3259_pp0_iter18_reg | or_ln378_1_reg_3252_pp0_iter18_reg);

assign or_ln386_fu_1867_p2 = (y_is_int_fu_1829_p9 | y_is_inf_fu_1715_p2);

assign or_ln431_1_fu_1966_p2 = (or_ln431_fu_1960_p2 | and_ln431_3_fu_1955_p2);

assign or_ln431_2_fu_1972_p2 = (or_ln431_1_fu_1966_p2 | and_ln431_1_fu_1944_p2);

assign or_ln431_fu_1960_p2 = (and_ln431_fu_1938_p2 | and_ln431_2_fu_1949_p2);

assign or_ln438_1_fu_2006_p2 = (or_ln438_fu_2000_p2 | and_ln438_3_fu_1994_p2);

assign or_ln438_2_fu_2012_p2 = (or_ln438_1_fu_2006_p2 | and_ln438_fu_1978_p2);

assign or_ln438_fu_2000_p2 = (and_ln438_2_fu_1989_p2 | and_ln438_1_fu_1983_p2);

assign or_ln628_fu_2767_p2 = (icmp_ln628_1_reg_3400 | and_ln628_fu_2763_p2);

assign out_exp_fu_2772_p2 = (trunc_ln657_reg_3415 + 11'd1023);

assign out_sig_fu_2708_p3 = ((tmp_28_fu_2646_p3[0:0] == 1'b1) ? tmp_3_fu_2688_p4 : tmp_12_fu_2698_p4);

assign pow_reduce_anonymous_namespace_log0_lut_table_array_address0 = zext_ln502_reg_2993_pp0_iter7_reg;

assign pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_address0 = zext_ln502_fu_704_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_address0 = zext_ln46_2_fu_1330_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_address0 = zext_ln46_3_fu_1334_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_address0 = zext_ln46_4_fu_1338_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_address0 = zext_ln46_5_fu_1342_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_address0 = zext_ln46_6_fu_1404_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_address0 = zext_ln46_fu_1322_p1;

assign pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_address0 = zext_ln46_1_fu_1326_p1;

assign pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_address0 = zext_ln611_fu_2503_p1;

assign pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_address0 = zext_ln273_fu_2499_p1;

assign pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_address0 = zext_ln254_fu_2432_p1;

assign pow_reduce_anonymous_namespace_table_f_Z3_ap_ufixed_array_address1 = zext_ln249_fu_2427_p1;

assign r_exp_1_fu_2654_p2 = ($signed(r_exp_reg_3336_pp0_iter17_reg) + $signed(13'd8191));

assign r_exp_2_fu_2659_p3 = ((tmp_28_fu_2646_p3[0:0] == 1'b1) ? r_exp_reg_3336_pp0_iter17_reg : r_exp_1_fu_2654_p2);

assign r_exp_fu_2356_p3 = ((tmp_24_fu_2326_p3[0:0] == 1'b1) ? select_ln563_fu_2348_p3 : tmp_9_cast_fu_2317_p4);

assign r_sign_fu_2121_p2 = (y_is_odd_1_fu_2102_p9 & x_is_neg_reg_3239);

assign retval_2_fu_2905_p18 = t_3_fu_2777_p4;

assign retval_2_fu_2905_p19 = 'bx;

assign retval_2_fu_2905_p20 = {{{{{{{{or_ln378_1_reg_3252_pp0_iter18_reg}, {and_ln342_fu_2799_p2}}, {and_ln386_1_fu_2809_p2}}, {and_ln431_4_fu_2825_p2}}, {and_ln438_4_fu_2836_p2}}, {and_ln629_fu_2853_p2}}, {and_ln629_1_fu_2863_p2}}, {and_ln645_1_fu_2880_p2}};

assign retval_2_fu_2905_p4 = t_fu_2720_p3;

assign select_ln42_fu_816_p3 = ((tmp_6_reg_3031[0:0] == 1'b1) ? tmp_4_fu_804_p3 : zext_ln42_2_fu_812_p1);

assign select_ln545_fu_2135_p3 = ((tmp_1_reg_3244[0:0] == 1'b1) ? sext_ln545_fu_2131_p1 : m_exp_reg_3223);

assign select_ln553_1_fu_2242_p3 = ((tmp_22_fu_2209_p3[0:0] == 1'b1) ? shl_ln553_fu_2232_p2 : ashr_ln553_fu_2237_p2);

assign select_ln553_fu_2217_p3 = ((tmp_22_fu_2209_p3[0:0] == 1'b1) ? m_exp_reg_3223 : sext_ln545_fu_2131_p1);

assign select_ln563_fu_2348_p3 = ((icmp_ln563_fu_2336_p2[0:0] == 1'b1) ? add_ln563_1_fu_2342_p2 : tmp_9_cast_fu_2317_p4);

assign sext_ln525_1_fu_1620_p1 = $signed(log_sum_1_fu_1560_p2);

assign sext_ln525_fu_1616_p1 = $signed(shl_ln2_fu_1608_p3);

assign sext_ln545_1_fu_2141_p1 = $signed(select_ln545_fu_2135_p3);

assign sext_ln545_fu_2131_p1 = sub_ln545_fu_2126_p2;

assign sext_ln552_fu_2197_p1 = m_exp_reg_3223;

assign sext_ln553_fu_2224_p1 = $signed(select_ln553_fu_2217_p3);

assign sext_ln628_fu_2297_p1 = $signed(m_fix_back_fu_2190_p3);

assign shl_ln1_fu_1581_p3 = {{tmp_20_reg_3177}, {45'd0}};

assign shl_ln2_fu_1608_p3 = {{Elog2_fu_604_p2}, {30'd0}};

assign shl_ln3_fu_2306_p3 = {{tmp_23_reg_3316_pp0_iter12_reg}, {18'd131072}};

assign shl_ln44_10_fu_1357_p3 = {{tmp_18_reg_3126}, {64'd0}};

assign shl_ln44_11_fu_1386_p3 = {{mul_ln44_6_fu_638_p2}, {26'd0}};

assign shl_ln44_1_fu_900_p3 = {{tmp_7_reg_3048}, {14'd0}};

assign shl_ln44_2_fu_929_p3 = {{mul_ln44_1_fu_634_p2}, {1'd0}};

assign shl_ln44_3_fu_1274_p3 = {{mul_ln44_5_fu_646_p2}, {21'd0}};

assign shl_ln44_4_fu_980_p3 = {{trunc_ln39_1_reg_3064}, {25'd0}};

assign shl_ln44_5_fu_1010_p3 = {{mul_ln44_2_fu_650_p2}, {6'd0}};

assign shl_ln44_6_fu_1069_p3 = {{tmp_8_reg_3075}, {34'd0}};

assign shl_ln44_7_fu_1098_p3 = {{mul_ln44_3_fu_658_p2}, {11'd0}};

assign shl_ln44_8_fu_1157_p3 = {{tmp_11_reg_3092}, {44'd0}};

assign shl_ln44_9_fu_1186_p3 = {{mul_ln44_4_fu_654_p2}, {16'd0}};

assign shl_ln44_s_fu_1245_p3 = {{tmp_15_reg_3109}, {54'd0}};

assign shl_ln4_fu_2628_p3 = {{add_ln616_fu_2613_p2}, {49'd0}};

assign shl_ln545_fu_2154_p2 = m_frac_l_reg_3282 << zext_ln545_fu_2145_p1;

assign shl_ln546_fu_2178_p2 = m_fix_l_fu_2167_p3 << zext_ln546_fu_2174_p1;

assign shl_ln552_fu_2204_p2 = m_frac_l_reg_3282 << zext_ln552_fu_2200_p1;

assign shl_ln553_fu_2232_p2 = m_frac_l_reg_3282 << zext_ln553_fu_2228_p1;

assign shl_ln_fu_823_p3 = {{trunc_ln39_reg_3026}, {25'd0}};

assign sub_ln422_fu_1920_p2 = (12'd1075 - zext_ln486_1_fu_1673_p1);

assign sub_ln44_1_fu_941_p2 = (add_ln44_1_fu_915_p2 - zext_ln44_7_fu_937_p1);

assign sub_ln44_2_fu_1022_p2 = (add_ln44_2_fu_995_p2 - zext_ln44_12_fu_1018_p1);

assign sub_ln44_3_fu_1110_p2 = (add_ln44_3_fu_1084_p2 - zext_ln44_17_fu_1106_p1);

assign sub_ln44_4_fu_1198_p2 = (add_ln44_4_fu_1172_p2 - zext_ln44_22_fu_1194_p1);

assign sub_ln44_5_fu_1286_p2 = (add_ln44_5_fu_1260_p2 - zext_ln44_27_fu_1282_p1);

assign sub_ln44_6_fu_1398_p2 = (add_ln44_6_fu_1372_p2 - zext_ln44_32_fu_1394_p1);

assign sub_ln44_fu_853_p2 = (add_ln44_fu_834_p2 - zext_ln44_2_fu_849_p1);

assign sub_ln522_fu_1592_p2 = (shl_ln1_fu_1581_p3 - zext_ln522_1_fu_1588_p1);

assign sub_ln545_fu_2126_p2 = (11'd1023 - es_exp_reg_3218);

assign sub_ln574_fu_2378_p2 = (m_fix_reg_3311_pp0_iter14_reg - m_fix_a_fu_2368_p4);

assign t_1_fu_2741_p3 = {{r_sign_reg_3303_pp0_iter18_reg}, {63'd9218868437227405312}};

assign t_2_fu_2752_p3 = {{r_sign_reg_3303_pp0_iter18_reg}, {63'd0}};

assign t_3_fu_2777_p4 = {{{r_sign_reg_3303_pp0_iter18_reg}, {out_exp_fu_2772_p2}}, {out_sig_reg_3410}};

assign t_fu_2720_p3 = {{r_sign_reg_3303_pp0_iter18_reg}, {63'd4607182418800017408}};

assign tmp_12_fu_2698_p4 = {{add_ln616_1_fu_2640_p2[104:53]}};

assign tmp_1_fu_1763_p3 = m_exp_fu_1677_p2[32'd11];

assign tmp_22_fu_2209_p3 = sub_ln545_fu_2126_p2[32'd10];

assign tmp_24_fu_2326_p3 = grp_fu_2949_p3[32'd30];

assign tmp_25_fu_2479_p4 = {{mul_ln258_fu_618_p2[78:59]}};

assign tmp_26_fu_2519_p4 = {{pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_q0[41:2]}};

assign tmp_27_fu_2563_p4 = {{mul_ln277_fu_622_p2[92:57]}};

assign tmp_28_fu_2646_p3 = add_ln616_1_fu_2640_p2[32'd106];

assign tmp_29_fu_2666_p4 = {{r_exp_2_fu_2659_p3[12:10]}};

assign tmp_3_fu_2688_p4 = {{add_ln616_1_fu_2640_p2[105:54]}};

assign tmp_4_fu_804_p3 = {{1'd1}, {zext_ln42_1_fu_800_p1}};

assign tmp_9_cast_fu_2317_p4 = {{grp_fu_2949_p3[30:18]}};

assign tmp_s_fu_781_p3 = {{mul_ln516_reg_3014}, {16'd0}};

assign trunc_ln39_1_fu_957_p1 = sub_ln44_1_fu_941_p2[75:0];

assign trunc_ln39_fu_762_p1 = mul_ln516_fu_630_p2[49:0];

assign trunc_ln545_1_fu_2163_p1 = shl_ln545_fu_2154_p2[129:0];

assign trunc_ln545_fu_2159_p1 = ashr_ln545_fu_2149_p2[129:0];

assign trunc_ln563_fu_2333_p1 = grp_fu_2949_p3[17:0];

assign trunc_ln657_fu_2716_p1 = r_exp_2_fu_2659_p3[10:0];

assign x_abs_greater_1_fu_1915_p2 = (tmp_2_reg_3206 ^ 1'd1);

assign x_is_0_fu_1453_p2 = ((bs_exp_reg_2965_pp0_iter8_reg == 11'd0) ? 1'b1 : 1'b0);

assign x_is_1_fu_1443_p2 = (icmp_ln340_fu_1437_p2 & icmp_ln340_1_reg_3003_pp0_iter8_reg);

assign x_is_NaN_fu_1733_p2 = (icmp_ln18_4_reg_3009_pp0_iter9_reg & icmp_ln18_3_reg_3193);

assign x_is_inf_fu_1737_p2 = (icmp_ln340_1_reg_3003_pp0_iter9_reg & icmp_ln18_3_reg_3193);

assign x_is_n1_fu_1699_p2 = (x_is_1_reg_3187 & tmp_reg_2980_pp0_iter9_reg);

assign x_is_neg_fu_1752_p2 = (xor_ln357_fu_1746_p2 & tmp_reg_2980_pp0_iter9_reg);

assign x_is_p1_fu_1694_p2 = (xor_ln341_fu_1689_p2 & x_is_1_reg_3187);

assign xor_ln341_fu_1689_p2 = (tmp_reg_2980_pp0_iter9_reg ^ 1'd1);

assign xor_ln342_fu_2814_p2 = (x_is_n1_reg_3233_pp0_iter18_reg ^ 1'd1);

assign xor_ln357_fu_1746_p2 = (or_ln357_fu_1741_p2 ^ 1'd1);

assign xor_ln373_fu_1815_p2 = (or_ln373_fu_1809_p2 ^ 1'd1);

assign xor_ln386_1_fu_2793_p2 = (or_ln386_3_fu_2789_p2 ^ 1'd1);

assign xor_ln386_2_fu_2804_p2 = (or_ln378_1_reg_3252_pp0_iter18_reg ^ 1'd1);

assign xor_ln386_fu_1873_p2 = (or_ln386_fu_1867_p2 ^ 1'd1);

assign xor_ln421_fu_2076_p2 = (icmp_ln421_fu_2061_p2 ^ 1'd1);

assign xor_ln431_fu_2731_p2 = (or_ln431_2_reg_3270_pp0_iter18_reg ^ 1'd1);

assign xor_ln438_fu_2736_p2 = (or_ln438_2_reg_3276_pp0_iter18_reg ^ 1'd1);

assign xor_ln628_fu_2869_p2 = (or_ln628_fu_2767_p2 ^ 1'd1);

assign xor_ln629_fu_2858_p2 = (tmp_30_reg_3292_pp0_iter18_reg ^ 1'd1);

assign y_is_0_fu_1683_p2 = ((es_exp_fu_1661_p3 == 11'd0) ? 1'b1 : 1'b0);

assign y_is_NaN_fu_1727_p2 = (icmp_ln18_fu_1703_p2 & icmp_ln18_2_fu_1721_p2);

assign y_is_inf_fu_1715_p2 = (icmp_ln18_fu_1703_p2 & icmp_ln18_1_fu_1709_p2);

assign y_is_int_fu_1829_p4 = ((and_ln373_1_fu_1797_p2 == 52'd0) ? 1'b1 : 1'b0);

assign y_is_int_fu_1829_p7 = 'bx;

assign y_is_int_fu_1829_p8 = {{icmp_ln372_fu_1757_p2}, {xor_ln373_fu_1815_p2}};

assign y_is_ninf_fu_1909_p2 = (y_is_inf_fu_1715_p2 & es_sign_fu_1653_p3);

assign y_is_odd_1_fu_2102_p7 = 'bx;

assign y_is_odd_1_fu_2102_p8 = {{icmp_ln421_fu_2061_p2}, {and_ln422_1_fu_2088_p2}};

assign y_is_odd_fu_1930_p2 = $signed(sub_ln422_fu_1920_p2);

assign y_is_pinf_fu_1903_p2 = (y_is_pos_fu_1897_p2 & y_is_inf_fu_1715_p2);

assign y_is_pos_fu_1897_p2 = (es_sign_fu_1653_p3 ^ 1'd1);

assign z1_fu_774_p3 = {{mul_ln516_reg_3014}, {17'd0}};

assign z3_fu_961_p3 = {{sub_ln44_1_reg_3053}, {1'd0}};

assign zext_ln194_1_fu_1488_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_q0;

assign zext_ln194_2_fu_1492_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_q0;

assign zext_ln194_3_fu_1496_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_17_6_64_array_q0;

assign zext_ln194_4_fu_1500_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_22_6_64_array_q0;

assign zext_ln194_5_fu_1504_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_27_6_64_array_q0;

assign zext_ln194_6_fu_1508_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_32_6_64_array_q0;

assign zext_ln194_fu_1484_p1 = pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_q0;

assign zext_ln209_1_fu_1546_p1 = add_ln209_4_fu_1540_p2;

assign zext_ln209_2_fu_1556_p1 = add_ln209_5_fu_1550_p2;

assign zext_ln209_fu_1524_p1 = add_ln209_1_fu_1518_p2;

assign zext_ln249_fu_2427_p1 = Z4_ind_fu_2417_p4;

assign zext_ln250_1_fu_2450_p1 = f_Z4_fu_2437_p4;

assign zext_ln250_fu_2447_p1 = Z4_reg_3360;

assign zext_ln254_fu_2432_p1 = Z3_fu_2403_p4;

assign zext_ln255_fu_2507_p1 = exp_Z3_m_1_reg_3375;

assign zext_ln261_1_fu_2489_p1 = tmp_25_fu_2479_p4;

assign zext_ln261_fu_2510_p1 = add_ln261_reg_3380;

assign zext_ln273_fu_2499_p1 = Z2_reg_3348;

assign zext_ln280_1_fu_2583_p1 = add_ln280_fu_2577_p2;

assign zext_ln280_2_fu_2573_p1 = tmp_27_fu_2563_p4;

assign zext_ln280_fu_2559_p1 = and_ln_fu_2548_p5;

assign zext_ln373_fu_1787_p1 = add_ln373_fu_1781_p2;

assign zext_ln40_1_fu_968_p1 = z3_fu_961_p3;

assign zext_ln40_2_fu_1058_p1 = z4_reg_3069;

assign zext_ln40_3_fu_1146_p1 = tmp_10_reg_3086;

assign zext_ln40_4_fu_1234_p1 = tmp_14_reg_3103;

assign zext_ln40_5_fu_1346_p1 = tmp_17_reg_3120;

assign zext_ln40_fu_889_p1 = z2_reg_3036;

assign zext_ln42_1_fu_800_p1 = z1_fu_774_p3;

assign zext_ln42_2_cast_fu_792_p3 = {{1'd1}, {zext_ln42_fu_788_p1}};

assign zext_ln42_2_fu_812_p1 = zext_ln42_2_cast_fu_792_p3;

assign zext_ln42_fu_788_p1 = tmp_s_fu_781_p3;

assign zext_ln44_12_fu_1018_p1 = shl_ln44_5_fu_1010_p3;

assign zext_ln44_13_fu_1076_p1 = shl_ln44_6_fu_1069_p3;

assign zext_ln44_14_fu_1080_p1 = eZ_2_fu_1061_p3;

assign zext_ln44_17_fu_1106_p1 = shl_ln44_7_fu_1098_p3;

assign zext_ln44_18_fu_1164_p1 = shl_ln44_8_fu_1157_p3;

assign zext_ln44_19_fu_1168_p1 = eZ_3_fu_1149_p3;

assign zext_ln44_22_fu_1194_p1 = shl_ln44_9_fu_1186_p3;

assign zext_ln44_23_fu_1252_p1 = shl_ln44_s_fu_1245_p3;

assign zext_ln44_24_fu_1256_p1 = eZ_4_fu_1237_p3;

assign zext_ln44_27_fu_1282_p1 = shl_ln44_3_fu_1274_p3;

assign zext_ln44_28_fu_1364_p1 = shl_ln44_10_fu_1357_p3;

assign zext_ln44_29_fu_1368_p1 = eZ_5_fu_1349_p3;

assign zext_ln44_2_fu_849_p1 = mul_ln44_fu_843_p2;

assign zext_ln44_32_fu_1394_p1 = shl_ln44_11_fu_1386_p3;

assign zext_ln44_3_fu_907_p1 = shl_ln44_1_fu_900_p3;

assign zext_ln44_4_fu_911_p1 = eZ_fu_892_p3;

assign zext_ln44_7_fu_937_p1 = shl_ln44_2_fu_929_p3;

assign zext_ln44_8_fu_987_p1 = shl_ln44_4_fu_980_p3;

assign zext_ln44_9_fu_991_p1 = eZ_1_fu_972_p3;

assign zext_ln44_fu_830_p1 = shl_ln_fu_823_p3;

assign zext_ln46_1_fu_1326_p1 = a_1_reg_3042_pp0_iter7_reg;

assign zext_ln46_2_fu_1330_p1 = a_2_reg_3058_pp0_iter7_reg;

assign zext_ln46_3_fu_1334_p1 = tmp_9_reg_3080_pp0_iter7_reg;

assign zext_ln46_4_fu_1338_p1 = tmp_13_reg_3097_pp0_iter7_reg;

assign zext_ln46_5_fu_1342_p1 = tmp_16_reg_3114_pp0_iter7_reg;

assign zext_ln46_6_fu_1404_p1 = tmp_19_reg_3131;

assign zext_ln46_fu_1322_p1 = a_reg_3020_pp0_iter7_reg;

assign zext_ln485_fu_735_p1 = b_frac_1_fu_728_p3;

assign zext_ln486_1_fu_1673_p1 = es_exp_fu_1661_p3;

assign zext_ln486_fu_1428_p1 = bs_exp_reg_2965_pp0_iter8_reg;

assign zext_ln502_fu_704_p1 = index0_fu_694_p4;

assign zext_ln522_1_fu_1588_p1 = lshr_ln_fu_1571_p4;

assign zext_ln522_fu_1566_p1 = tmp_21_reg_3182;

assign zext_ln525_fu_1630_p1 = lshr_ln522_1_fu_1598_p4;

assign zext_ln532_fu_2026_p1 = e_frac_fu_2018_p3;

assign zext_ln545_fu_2145_p1 = $unsigned(sext_ln545_1_fu_2141_p1);

assign zext_ln546_fu_2174_p1 = $unsigned(sext_ln545_1_fu_2141_p1);

assign zext_ln549_fu_2261_p1 = empty_fu_2257_p1;

assign zext_ln552_fu_2200_p1 = $unsigned(sext_ln552_fu_2197_p1);

assign zext_ln553_fu_2228_p1 = $unsigned(sext_ln553_fu_2224_p1);

assign zext_ln611_fu_2503_p1 = m_diff_hi_reg_3343_pp0_iter16_reg;

assign zext_ln616_2_fu_2636_p1 = mul_ln616_fu_626_p2;

always @ (posedge ap_clk) begin
    zext_ln502_reg_2993[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln502_reg_2993_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln502_reg_2993_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln502_reg_2993_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln502_reg_2993_pp0_iter4_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln502_reg_2993_pp0_iter5_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln502_reg_2993_pp0_iter6_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln502_reg_2993_pp0_iter7_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    exp_Z3_m_1_reg_3375[34:26] <= 9'b000000000;
end

endmodule //SABR_pow_generic_double_s
