// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="SABR_SABR,hls_ip_2024_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7s15-cpga196-2,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.052030,HLS_SYN_LAT=494961,HLS_SYN_TPT=none,HLS_SYN_MEM=60,HLS_SYN_DSP=0,HLS_SYN_FF=52065,HLS_SYN_LUT=82428,HLS_VERSION=2024_2}" *)

module SABR (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 90'd1;
parameter    ap_ST_fsm_state2 = 90'd2;
parameter    ap_ST_fsm_state3 = 90'd4;
parameter    ap_ST_fsm_state4 = 90'd8;
parameter    ap_ST_fsm_state5 = 90'd16;
parameter    ap_ST_fsm_state6 = 90'd32;
parameter    ap_ST_fsm_state7 = 90'd64;
parameter    ap_ST_fsm_state8 = 90'd128;
parameter    ap_ST_fsm_state9 = 90'd256;
parameter    ap_ST_fsm_state10 = 90'd512;
parameter    ap_ST_fsm_state11 = 90'd1024;
parameter    ap_ST_fsm_state12 = 90'd2048;
parameter    ap_ST_fsm_state13 = 90'd4096;
parameter    ap_ST_fsm_state14 = 90'd8192;
parameter    ap_ST_fsm_state15 = 90'd16384;
parameter    ap_ST_fsm_state16 = 90'd32768;
parameter    ap_ST_fsm_state17 = 90'd65536;
parameter    ap_ST_fsm_state18 = 90'd131072;
parameter    ap_ST_fsm_state19 = 90'd262144;
parameter    ap_ST_fsm_state20 = 90'd524288;
parameter    ap_ST_fsm_state21 = 90'd1048576;
parameter    ap_ST_fsm_state22 = 90'd2097152;
parameter    ap_ST_fsm_state23 = 90'd4194304;
parameter    ap_ST_fsm_state24 = 90'd8388608;
parameter    ap_ST_fsm_state25 = 90'd16777216;
parameter    ap_ST_fsm_state26 = 90'd33554432;
parameter    ap_ST_fsm_state27 = 90'd67108864;
parameter    ap_ST_fsm_state28 = 90'd134217728;
parameter    ap_ST_fsm_state29 = 90'd268435456;
parameter    ap_ST_fsm_state30 = 90'd536870912;
parameter    ap_ST_fsm_state31 = 90'd1073741824;
parameter    ap_ST_fsm_state32 = 90'd2147483648;
parameter    ap_ST_fsm_state33 = 90'd4294967296;
parameter    ap_ST_fsm_state34 = 90'd8589934592;
parameter    ap_ST_fsm_state35 = 90'd17179869184;
parameter    ap_ST_fsm_state36 = 90'd34359738368;
parameter    ap_ST_fsm_state37 = 90'd68719476736;
parameter    ap_ST_fsm_state38 = 90'd137438953472;
parameter    ap_ST_fsm_state39 = 90'd274877906944;
parameter    ap_ST_fsm_state40 = 90'd549755813888;
parameter    ap_ST_fsm_state41 = 90'd1099511627776;
parameter    ap_ST_fsm_state42 = 90'd2199023255552;
parameter    ap_ST_fsm_state43 = 90'd4398046511104;
parameter    ap_ST_fsm_state44 = 90'd8796093022208;
parameter    ap_ST_fsm_state45 = 90'd17592186044416;
parameter    ap_ST_fsm_state46 = 90'd35184372088832;
parameter    ap_ST_fsm_state47 = 90'd70368744177664;
parameter    ap_ST_fsm_state48 = 90'd140737488355328;
parameter    ap_ST_fsm_state49 = 90'd281474976710656;
parameter    ap_ST_fsm_state50 = 90'd562949953421312;
parameter    ap_ST_fsm_state51 = 90'd1125899906842624;
parameter    ap_ST_fsm_state52 = 90'd2251799813685248;
parameter    ap_ST_fsm_state53 = 90'd4503599627370496;
parameter    ap_ST_fsm_state54 = 90'd9007199254740992;
parameter    ap_ST_fsm_state55 = 90'd18014398509481984;
parameter    ap_ST_fsm_state56 = 90'd36028797018963968;
parameter    ap_ST_fsm_state57 = 90'd72057594037927936;
parameter    ap_ST_fsm_state58 = 90'd144115188075855872;
parameter    ap_ST_fsm_state59 = 90'd288230376151711744;
parameter    ap_ST_fsm_state60 = 90'd576460752303423488;
parameter    ap_ST_fsm_state61 = 90'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 90'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 90'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 90'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 90'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 90'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 90'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 90'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 90'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 90'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 90'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 90'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 90'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 90'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 90'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 90'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 90'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 90'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 90'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 90'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 90'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 90'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 90'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 90'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 90'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 90'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 90'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 90'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 90'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 90'd618970019642690137449562112;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 8;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [89:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] S;
wire   [63:0] V;
wire   [63:0] S0;
wire   [63:0] r;
wire   [63:0] sigma_init;
wire   [63:0] alpha;
wire   [63:0] beta;
wire   [63:0] rho;
wire   [63:0] T;
wire   [63:0] random_increments;
wire   [63:0] grp_fu_241_p2;
reg   [63:0] reg_267;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state76;
wire    ap_CS_fsm_state82;
wire    ap_CS_fsm_state88;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done;
reg   [63:0] T_read_reg_307;
reg    ap_block_state1;
reg   [63:0] rho_read_reg_312;
wire    ap_CS_fsm_state20;
wire   [63:0] grp_fu_250_p2;
reg   [63:0] deltat_reg_319;
wire    ap_CS_fsm_state32;
wire   [63:0] grp_fu_235_p2;
reg   [63:0] sub_reg_326;
reg   [63:0] alpha_read_reg_331;
wire    ap_CS_fsm_state70;
reg   [63:0] r_read_reg_338;
wire   [63:0] grp_fu_246_p2;
reg   [63:0] mul3_reg_343;
reg   [63:0] random_increments_read_reg_348;
wire    ap_CS_fsm_state87;
reg   [63:0] V_read_reg_353;
reg   [63:0] S_read_reg_358;
reg   [58:0] trunc_ln_reg_363;
reg   [58:0] trunc_ln12_1_reg_368;
wire   [63:0] empty_fu_297_p1;
reg   [63:0] empty_reg_373;
wire   [63:0] empty_322_fu_302_p1;
reg   [63:0] empty_322_reg_378;
reg   [63:0] add_reg_383;
reg   [63:0] beta_read_reg_388;
wire    ap_CS_fsm_state89;
wire   [63:0] grp_fu_255_p2;
reg   [63:0] tmp_reg_393;
wire   [63:0] grp_fu_261_p2;
reg   [63:0] tmp_s_reg_398;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_idle;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_ready;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWID;
wire   [31:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWUSER;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WVALID;
wire   [255:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WDATA;
wire   [31:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WSTRB;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WLAST;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WID;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WUSER;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARID;
wire   [31:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARUSER;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_RREADY;
wire    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_BREADY;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_done;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_idle;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_ready;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWID;
wire   [31:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWUSER;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WVALID;
wire   [255:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WDATA;
wire   [31:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WSTRB;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WLAST;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WID;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WUSER;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARID;
wire   [31:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARUSER;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_RREADY;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_BREADY;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_din0;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_din1;
wire   [0:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_opcode;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_ce;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_din0;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_din1;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_ce;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_din0;
wire   [63:0] grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_din1;
wire    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_ce;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
reg   [63:0] gmem_0_AWADDR;
reg   [31:0] gmem_0_AWLEN;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
reg   [255:0] gmem_0_WDATA;
reg   [31:0] gmem_0_WSTRB;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [255:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg    grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start_reg;
reg    grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start_reg;
wire    ap_CS_fsm_state90;
reg   [63:0] grp_fu_235_p0;
reg   [63:0] grp_fu_235_p1;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state83;
reg   [63:0] grp_fu_241_p0;
reg   [63:0] grp_fu_241_p1;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state71;
wire    ap_CS_fsm_state77;
reg   [63:0] grp_fu_246_p0;
reg   [63:0] grp_fu_246_p1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state33;
reg   [1:0] grp_fu_235_opcode;
reg    grp_fu_235_ce;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state84;
wire    ap_CS_fsm_state85;
wire    ap_CS_fsm_state86;
reg    grp_fu_241_ce;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state72;
wire    ap_CS_fsm_state73;
wire    ap_CS_fsm_state74;
wire    ap_CS_fsm_state75;
wire    ap_CS_fsm_state78;
wire    ap_CS_fsm_state79;
wire    ap_CS_fsm_state80;
wire    ap_CS_fsm_state81;
reg    grp_fu_246_ce;
reg    grp_fu_255_ce;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg    grp_fu_261_ce;
reg   [89:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
reg    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
reg    ap_ST_fsm_state90_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 90'd1;
#0 grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start_reg = 1'b0;
#0 grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start_reg = 1'b0;
end

SABR_SABR_Pipeline_VITIS_LOOP_12_1 grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start),
    .ap_done(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done),
    .ap_idle(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_idle),
    .ap_ready(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(1'b0),
    .m_axi_gmem_0_ARADDR(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(1'b0),
    .m_axi_gmem_0_RREADY(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(256'd0),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(9'd0),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .empty_75(empty_322_reg_378),
    .empty(empty_reg_373),
    .sext_ln12(trunc_ln_reg_363),
    .trunc_ln12_1_cast(trunc_ln12_1_reg_368)
);

SABR_SABR_Pipeline_VITIS_LOOP_17_2 grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start),
    .ap_done(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_done),
    .ap_idle(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_idle),
    .ap_ready(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .S(S_read_reg_358),
    .V(V_read_reg_353),
    .random_increments(random_increments_read_reg_348),
    .tmp(tmp_reg_393),
    .rho(rho_read_reg_312),
    .tmp_s(tmp_s_reg_398),
    .add(add_reg_383),
    .beta(beta_read_reg_388),
    .alpha(alpha_read_reg_331),
    .mul4(reg_267),
    .grp_fu_235_p_din0(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_din0),
    .grp_fu_235_p_din1(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_din1),
    .grp_fu_235_p_opcode(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_opcode),
    .grp_fu_235_p_dout0(grp_fu_235_p2),
    .grp_fu_235_p_ce(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_ce),
    .grp_fu_241_p_din0(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_din0),
    .grp_fu_241_p_din1(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_din1),
    .grp_fu_241_p_dout0(grp_fu_241_p2),
    .grp_fu_241_p_ce(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_ce),
    .grp_fu_246_p_din0(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_din0),
    .grp_fu_246_p_din1(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_din1),
    .grp_fu_246_p_dout0(grp_fu_246_p2),
    .grp_fu_246_p_ce(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_ce)
);

SABR_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .S(S),
    .V(V),
    .S0(S0),
    .r(r),
    .sigma_init(sigma_init),
    .alpha(alpha),
    .beta(beta),
    .rho(rho),
    .T(T),
    .random_increments(random_increments),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

SABR_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 256 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARADDR),
    .I_CH0_ARLEN(grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(gmem_0_AWADDR),
    .I_CH0_AWLEN(gmem_0_AWLEN),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(gmem_0_WDATA),
    .I_CH0_WSTRB(gmem_0_WSTRB),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

SABR_dadddsub_64ns_64ns_64_6_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadddsub_64ns_64ns_64_6_full_dsp_1_U81(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_235_p0),
    .din1(grp_fu_235_p1),
    .opcode(grp_fu_235_opcode),
    .ce(grp_fu_235_ce),
    .dout(grp_fu_235_p2)
);

SABR_dmul_64ns_64ns_64_6_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_6_max_dsp_1_U82(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_241_p0),
    .din1(grp_fu_241_p1),
    .ce(grp_fu_241_ce),
    .dout(grp_fu_241_p2)
);

SABR_dmul_64ns_64ns_64_6_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_6_max_dsp_1_U83(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_246_p0),
    .din1(grp_fu_246_p1),
    .ce(grp_fu_246_ce),
    .dout(grp_fu_246_p2)
);

SABR_ddiv_64ns_64ns_64_31_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 31 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
ddiv_64ns_64ns_64_31_no_dsp_1_U84(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(T_read_reg_307),
    .din1(64'd4632233691727265792),
    .ce(1'b1),
    .dout(grp_fu_250_p2)
);

SABR_dsqrt_64ns_64ns_64_57_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 57 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsqrt_64ns_64ns_64_57_no_dsp_1_U85(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(64'd0),
    .din1(deltat_reg_319),
    .ce(grp_fu_255_ce),
    .dout(grp_fu_255_p2)
);

SABR_dsqrt_64ns_64ns_64_57_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 57 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dsqrt_64ns_64ns_64_57_no_dsp_1_U86(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(64'd0),
    .din1(sub_reg_326),
    .ce(grp_fu_261_ce),
    .dout(grp_fu_261_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state90))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state87)) begin
            grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start_reg <= 1'b1;
        end else if ((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_ready == 1'b1)) begin
            grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state89)) begin
            grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start_reg <= 1'b1;
        end else if ((grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_ready == 1'b1)) begin
            grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state87)) begin
        S_read_reg_358 <= S;
        V_read_reg_353 <= V;
        empty_322_reg_378 <= empty_322_fu_302_p1;
        empty_reg_373 <= empty_fu_297_p1;
        random_increments_read_reg_348 <= random_increments;
        trunc_ln12_1_reg_368 <= {{V[63:5]}};
        trunc_ln_reg_363 <= {{S[63:5]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        T_read_reg_307 <= T;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state88))) begin
        add_reg_383 <= grp_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        alpha_read_reg_331 <= alpha;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state89)) begin
        beta_read_reg_388 <= beta;
        tmp_reg_393 <= grp_fu_255_p2;
        tmp_s_reg_398 <= grp_fu_261_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        deltat_reg_319 <= grp_fu_250_p2;
        sub_reg_326 <= grp_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state82)) begin
        mul3_reg_343 <= grp_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        r_read_reg_338 <= r;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state26) | ((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state88)))) begin
        reg_267 <= grp_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        rho_read_reg_312 <= rho;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

always @ (*) begin
    if ((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done == 1'b0)) begin
        ap_ST_fsm_state88_blk = 1'b1;
    end else begin
        ap_ST_fsm_state88_blk = 1'b0;
    end
end

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_done == 1'b0)) begin
        ap_ST_fsm_state90_blk = 1'b1;
    end else begin
        ap_ST_fsm_state90_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state90))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state90))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_ARVALID = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_ARVALID;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_AWADDR = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state88))) begin
        gmem_0_AWADDR = grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWADDR;
    end else begin
        gmem_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_AWLEN = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state88))) begin
        gmem_0_AWLEN = grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWLEN;
    end else begin
        gmem_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_AWVALID = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state88))) begin
        gmem_0_AWVALID = grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_AWVALID;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_BREADY = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state88))) begin
        gmem_0_BREADY = grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_BREADY;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_RREADY = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_RREADY;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_WDATA = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state88))) begin
        gmem_0_WDATA = grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WDATA;
    end else begin
        gmem_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_WSTRB = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state88))) begin
        gmem_0_WSTRB = grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WSTRB;
    end else begin
        gmem_0_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state89))) begin
        gmem_0_WVALID = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_m_axi_gmem_0_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state88))) begin
        gmem_0_WVALID = grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_m_axi_gmem_0_WVALID;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_235_ce = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state86) | (1'b1 == ap_CS_fsm_state85) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state32) | ((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state88)))) begin
        grp_fu_235_ce = 1'b1;
    end else begin
        grp_fu_235_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_235_opcode = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_235_opcode = 2'd1;
    end else if ((1'b1 == ap_CS_fsm_state83)) begin
        grp_fu_235_opcode = 2'd0;
    end else begin
        grp_fu_235_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_235_p0 = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state83)) begin
        grp_fu_235_p0 = reg_267;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_235_p0 = 64'd4607182418800017408;
    end else begin
        grp_fu_235_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_235_p1 = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_235_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state83)) begin
        grp_fu_235_p1 = 64'd4607182418800017408;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_235_p1 = reg_267;
    end else begin
        grp_fu_235_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_241_ce = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state79) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state86) | (1'b1 == ap_CS_fsm_state85) | (1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state83) | (1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state76) | (1'b1 == ap_CS_fsm_state26) | ((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state88)))) begin
        grp_fu_241_ce = 1'b1;
    end else begin
        grp_fu_241_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_241_p0 = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state83)) begin
        grp_fu_241_p0 = mul3_reg_343;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_241_p0 = deltat_reg_319;
    end else if ((1'b1 == ap_CS_fsm_state71)) begin
        grp_fu_241_p0 = alpha_read_reg_331;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_241_p0 = rho_read_reg_312;
    end else begin
        grp_fu_241_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_241_p1 = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_241_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state83)) begin
        grp_fu_241_p1 = deltat_reg_319;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_241_p1 = r_read_reg_338;
    end else if ((1'b1 == ap_CS_fsm_state71)) begin
        grp_fu_241_p1 = 64'd13826050856027422720;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_241_p1 = rho_read_reg_312;
    end else begin
        grp_fu_241_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_246_ce = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_ce;
    end else begin
        grp_fu_246_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_246_p0 = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_246_p0 = reg_267;
    end else begin
        grp_fu_246_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state90)) begin
        grp_fu_246_p1 = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_grp_fu_246_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        grp_fu_246_p1 = alpha_read_reg_331;
    end else begin
        grp_fu_246_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | ((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done 
    == 1'b0) & (1'b1 == ap_CS_fsm_state88)))) begin
        grp_fu_255_ce = 1'b0;
    end else begin
        grp_fu_255_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | ((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done 
    == 1'b0) & (1'b1 == ap_CS_fsm_state88)))) begin
        grp_fu_261_ce = 1'b0;
    end else begin
        grp_fu_261_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            if (((grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state88))) begin
                ap_NS_fsm = ap_ST_fsm_state89;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state88;
            end
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            if (((grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state90))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state90;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state79 = ap_CS_fsm[32'd78];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state80 = ap_CS_fsm[32'd79];

assign ap_CS_fsm_state81 = ap_CS_fsm[32'd80];

assign ap_CS_fsm_state82 = ap_CS_fsm[32'd81];

assign ap_CS_fsm_state83 = ap_CS_fsm[32'd82];

assign ap_CS_fsm_state84 = ap_CS_fsm[32'd83];

assign ap_CS_fsm_state85 = ap_CS_fsm[32'd84];

assign ap_CS_fsm_state86 = ap_CS_fsm[32'd85];

assign ap_CS_fsm_state87 = ap_CS_fsm[32'd86];

assign ap_CS_fsm_state88 = ap_CS_fsm[32'd87];

assign ap_CS_fsm_state89 = ap_CS_fsm[32'd88];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state90 = ap_CS_fsm[32'd89];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_322_fu_302_p1 = sigma_init;

assign empty_fu_297_p1 = S0;

assign grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start = grp_SABR_Pipeline_VITIS_LOOP_12_1_fu_184_ap_start_reg;

assign grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start = grp_SABR_Pipeline_VITIS_LOOP_17_2_fu_194_ap_start_reg;

endmodule //SABR
